swagger: "2.0"
info:
  version: "0.1"
  title: RealtyMaps API
  contact:
    name: RealtyMaps
    url: http://realtymaps.com
host: dev.realtymaps.com:4000
basePath: /api
schemes:
  - http
produces:
  - application/json

paths:
  /mls_config:
    x-swagger-router-controller: "route.mls_config"
    get:
      operationId: getAll
      summary: Get All MLS Configs
      responses:
        200:
          description: MLS config list
          schema:
            type: array
            items:
              $ref: "#/definitions/MlsConfig"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/ExpressError"
    post:
      operationId: create
      summary: Create MLS Config
      parameters:
        - name: mlsConfig
          in: body
          type: object
          required: true
          description: MLS config object
      responses:
        200:
          description: MLS create result
          type: boolean
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/ExpressError"
  /mls_config/{mlsConfigId}:
    x-swagger-router-controller: "route.mls_config"
    get:
      operationId: getById
      summary: Get MLS Config
      parameters:
        - name: mlsConfigId
          in: path
          type: string
          required: true
          description: MLS config ID (eg. swflmls)
      responses:
        200:
          description: MLS config
          schema:
            $ref: "#/definitions/MlsConfig"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/ExpressError"
    post:
      operationId: createById
      summary: Create MLS Config
      parameters:
        - name: mlsConfigId
          in: path
          type: string
          required: true
          description: New MLS config Id
        - name: mlsConfig
          in: body
          type: object
          required: true
          description: New MLS config object
      responses:
        200:
          description: MLS create result
          type: boolean
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/ExpressError"
    patch:
      operationId: update
      summary: Update MLS Config
      parameters:
        - name: mlsConfigId
          in: path
          type: string
          required: true
          description: Existing MLS config Id
        - name: mlsConfig
          in: body
          type: object
          required: true
          description: MLS config object
      responses:
        200:
          description: MLS update result
          type: boolean
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/ExpressError"
  /mls_config/{mlsConfigId}/propertyData:
    x-swagger-router-controller: "route.mls_config"
    patch:
      operationId: updatePropertyData
      summary: Update MLS Property Data
      parameters:
        - name: mlsConfigId
          in: path
          type: string
          required: true
          description: Existing MLS config Id
        - name: mlsConfig
          in: body
          type: object
          required: true
          description: MLS property data
      responses:
        200:
          description: MLS property data update result
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/ExpressError"
  /mls_config/{mlsConfigId}/serverInfo:
    x-swagger-router-controller: "route.mls_config"
    patch:
      operationId: updateServerInfo
      summary: Update MLS Server Info
      parameters:
        - name: mlsConfigId
          in: path
          type: string
          required: true
          description: Existing MLS config Id
        - name: mlsConfig
          in: body
          type: object
          required: true
          description: MLS server info
      responses:
        200:
          description: MLS server info update result
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/ExpressError"

  /mls/{mlsId}/databases:
    x-swagger-router-controller: "route.mls"
    get:
      operationId: getDatabaseList
      summary: List MLS databases
      parameters:
        - name: mlsId
          in: path
          type: string
          required: true
          description: MLS identifier (eg. swflmls)
      responses:
        200:
          description: MLS database list
          schema:
            type: array
            items:
              $ref: "#/definitions/MlsDatabase"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/ExpressError"

  /mls/{mlsId}/databases/{databaseId}:
    x-swagger-router-controller: "route.mls"
    get:
      operationId: getTableList
      summary: List MLS database tables
      parameters:
        - name: mlsId
          in: path
          type: string
          required: true
          description: MLS identifier (eg. swflmls)
        - name: databaseId
          in: path
          type: string
          required: true
          description: Database ResourceId (eg. Property)
      responses:
        200:
          description: MLS table list
          schema:
            type: array
            items:
              $ref: "#/definitions/MlsTable"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/ExpressError"

  /mls/{mlsId}/databases/{databaseId}/tables/{tableId}:
    x-swagger-router-controller: "route.mls"
    get:
      operationId: getColumnList
      summary: List MLS table columns
      parameters:
        - name: mlsId
          in: path
          type: string
          required: true
          description: MLS identifier (eg. swflmls)
        - name: databaseId
          in: path
          type: string
          required: true
          description: Database ResourceId (eg. Property)
        - name: tableId
          in: path
          type: string
          required: true
          description: Table ClassName (eg. RES)
      responses:
        200:
          description: MLS table list
          schema:
            type: array
            items:
              $ref: "#/definitions/MlsTable"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/ExpressError"

definitions:
  MlsConfig:
    type: 'object'
    properties:
      id:
        type: string
      name:
        type: string
      notes:
        type: string
      active:
        type: string
      username:
        type: string
      password:
        type: string
      url:
        type: string
      main_property_data:
        type: string #json
  MlsDatabase:
    type: 'object'
    properties:
      ResourceId:
        type: string
      VisibleName:
        type: string
      StandardName:
        type: string
      ObjectVersion:
        type: string
  MlsTable:
    type: 'object'
    properties:
      ClassName:
        type: string
      StandardName:
        type: string
      VisibleName:
        type: string
      TableVersion:
        type: string
  MlsColumn:
    type: 'object'
    properties:
      MetadataEntryID:
        type: string
      SystemName:
        type: string
      ShortName:
        type: string
      LongName:
        type: string
      DataType:
        type: string
  ExpressError:
    required:
      - alert
    properties:
      alert:
        type: object
        properties:
          msg:
            type: string


