#!/bin/sh
set -e
if [[ $IS_HEROKU ]]; then
  exit 0
fi
#or 4000
argPorts=${1:-"3000,4000"}
ports=(${argPorts//,/ })

for i in "${!ports[@]}"
do
  PID=$(./getRunningPID)
  if [[ -n $PID ]]; then
    kill $PID
    someThingWasKilled='true'
  else
    if [[ -z $someThingWasKilled ]];then
      echo "We're goodNothing running to stop."
    fi
  fi
done
