--
-- PostgreSQL database dump
--

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

SET search_path = public, pg_catalog;

-- some circumstances may have resulted in deed data populated in this table already.  If this is the case,
-- since this migration is intended to be an initial population of deed field data, let's make sure it's clean:
DELETE FROM config_data_source_fields WHERE data_source_id = 'CoreLogic' and data_source_type = 'county' and data_list_type = 'deed';

--
-- Data for Name: config_data_source_fields; Type: TABLE DATA; Schema: public; Owner: dev
--

INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (292, 'Fips Code', 'FipsCode', 'Fips Code', 'Character', '', 'FIPS_CODE', 'Federal Information Processing Standards codes, used to identify specific counties or political jurisdictions.', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (293, 'Apn Unformatted', 'ApnUnformatted', 'Apn Unformatted', 'Character', '', 'APN_UNFORMATTED', 'Assessor''s Parcel Identification in unformatted form. Most often a county unique key for identifying a parcel', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (294, 'Apn Formatted', 'ApnFormatted', 'Apn Formatted', 'Character', '', 'APN_FORMATTED', 'Assessor''s Parcel Identification in formatted form. Dashes or decimals added to break an APN into logical components', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (295, 'Apn Sequence Number', 'ApnSequenceNumber', 'Apn Sequence Number', 'Character', '', 'APN_SEQUENCE_NUMBER', 'Internal sequence number used to ensure "uniqueness" of the APN within a county.', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (296, 'Original Apn', 'OriginalApn', 'Original Apn', 'Character', '', 'ORIGINAL_APN', 'Assessor''s Parcel Identification Number as received from the source.', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (297, 'Account Number', 'AccountNumber', 'Account Number', 'Character', '', 'ACCOUNT_NUMBER', 'County of source number used primarily for billing. Not necessarily unique to a parcel number (i.e.: several parcels with one billing "account" number.', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (298, 'Owner Corporate Indicator Flag', 'OwnerCorporateIndicatorFlag', 'Owner Corporate Indicator Flag', 'Character', 'Lookup', 'OWNER_CORPORATE_INDICATOR_FLAG', 'Name of the property owner has been recognized as a corporation or business', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (299, 'Owner Buyer 1 Last Name', 'OwnerBuyer1LastName', 'Owner Buyer 1 Last Name', 'Character', '', 'OWNER_BUYER_1_LAST_NAME', 'Last name of the BUYER (1st OWNER)', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (300, 'Owner Buyer 1 First Name M I', 'OwnerBuyer1FirstNameMI', 'Owner Buyer 1 First Name M I', 'Character', '', 'OWNER_BUYER_1_FIRST_NAME_M_I', 'First name of the BUYER (1st OWNER)', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (301, 'Owner Buyer 2 Last Name', 'OwnerBuyer2LastName', 'Owner Buyer 2 Last Name', 'Character', '', 'OWNER_BUYER_2_LAST_NAME', 'Last name of the BUYER (2nd OWNER)', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (302, 'Owner Buyer 2 First Name M I', 'OwnerBuyer2FirstNameMI', 'Owner Buyer 2 First Name M I', 'Character', '', 'OWNER_BUYER_2_FIRST_NAME_M_I', 'First name of the BUYER (2nd OWNER)', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (303, 'Owner Etal Indicator Code', 'OwnerEtalIndicatorCode', 'Owner Etal Indicator Code', 'Character', 'Lookup', 'OWNER_ETAL_INDICATOR_CODE', 'Code indicates additional owners whose names were not supplied by the source', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (304, 'Owner Co Name', 'OwnerCoName', 'Owner Co Name', 'Character', '', 'OWNER_CO_NAME', 'Care of Name as supplied by the source', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (305, 'Owner Ownership Rights Code', 'OwnerOwnershipRightsCode', 'Owner Ownership Rights Code', 'Character', 'Lookup', 'OWNER_OWNERSHIP_RIGHTS_CODE', 'Form or method of property ownership (i.e.; joint tenancy)', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (306, 'Owner Relationship Type Code', 'OwnerRelationshipTypeCode', 'Owner Relationship Type Code', 'Character', 'Lookup', 'OWNER_RELATIONSHIP_TYPE_CODE', 'Relationship between multiple owners or marital status.', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (307, 'Partial Interest Indicator Flag', 'PartialInterestIndicatorFlag', 'Partial Interest Indicator Flag', 'Character', '', 'PARTIAL_INTEREST_INDICATOR_FLAG', 'An indicator showing the Owner/Buyer has a partial interest in the property', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (308, 'Absentee Indicator Code', 'AbsenteeIndicatorCode', 'Absentee Indicator Code', 'Character', 'Lookup', 'ABSENTEE_INDICATOR_CODE', 'Indicator to indetify if the owner lives at the residence. This field is not populated for non-residential parcels', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (309, 'Property House Number Prefix', 'PropertyHouseNumberPrefix', 'Property House Number Prefix', 'Character', '', 'PROPERTY_HOUSE_NUMBER_PREFIX', 'Digits found to the left of the house number of the property address', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (310, 'Property House Number', 'PropertyHouseNumber', 'Property House Number', 'Character', '', 'PROPERTY_HOUSE_NUMBER', 'House number of the property address (Numeric field with leading zeros, but can contain alpha characters)', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (311, 'Property House Number Suffix', 'PropertyHouseNumberSuffix', 'Property House Number Suffix', 'Character', '', 'PROPERTY_HOUSE_NUMBER_SUFFIX', 'Digits found to the right of the house number of the property address', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (312, 'Property Direction', 'PropertyDirection', 'Property Direction', 'Character', '', 'PROPERTY_DIRECTION', 'Name or number of the street. Numeric streets have 10 digits with leading zeros', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (313, 'Property Street Name', 'PropertyStreetName', 'Property Street Name', 'Character', '', 'PROPERTY_STREET_NAME', 'Mode of Type of street (i.e.; Ave, St Blvd)', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (314, 'Property Mode', 'PropertyMode', 'Property Mode', 'Character', '', 'PROPERTY_MODE', 'Direction of the street', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (315, 'Property Quadrant', 'PropertyQuadrant', 'Property Quadrant', 'Character', '', 'PROPERTY_QUADRANT', 'Represents the quadrant of the city. (i.e. 100 Temple St NW) AKA post direction', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (316, 'Property Apartment Unit Number', 'PropertyApartmentUnitNumber', 'Property Apartment Unit Number', 'Character', '', 'PROPERTY_APARTMENT_UNIT_NUMBER', 'The unit or suite number of the property address', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (317, 'Property City', 'PropertyCity', 'Property City', 'Character', '', 'PROPERTY_CITY', 'The city associated with the property address', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (318, 'Property State', 'PropertyState', 'Property State', 'Character', '', 'PROPERTY_STATE', 'Two letter USPS abbreviation of the state', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (319, 'Property Zipcode', 'PropertyZipcode', 'Property Zipcode', 'Character', '', 'PROPERTY_ZIPCODE', 'Nine digit code assigned by the USPS', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (320, 'Property Carrier Route', 'PropertyCarrierRoute', 'Property Carrier Route', 'Character', '', 'PROPERTY_CARRIER_ROUTE', 'Four digit code used by the local mail carrier to identify delivery path', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (321, 'Mail House Number Prefix', 'MailHouseNumberPrefix', 'Mail House Number Prefix', 'Character', '', 'MAIL_HOUSE_NUMBER_PREFIX', 'Digits found to the left of the house number of the mailing address', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (322, 'Mail House Number', 'MailHouseNumber', 'Mail House Number', 'Character', '', 'MAIL_HOUSE_NUMBER', 'House number of the mailing address (Numeric field with leading zeros, but can contain alpha characters)', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (323, 'Mail House Number Suffix', 'MailHouseNumberSuffix', 'Mail House Number Suffix', 'Character', '', 'MAIL_HOUSE_NUMBER_SUFFIX', 'Digits found to the right of the house number of the mailing address', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (324, 'Mail Street Direction', 'MailStreetDirection', 'Mail Street Direction', 'Character', '', 'MAIL_STREET_DIRECTION', 'Direction of the street', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (325, 'Mail Street Name', 'MailStreetName', 'Mail Street Name', 'Character', '', 'MAIL_STREET_NAME', 'Name or number of the street. Numeric streets have 10 digits with leading zeros', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (326, 'Mail Mode', 'MailMode', 'Mail Mode', 'Character', '', 'MAIL_MODE', 'Mode of Type of street (i.e.; Ave, St Blvd)', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (327, 'Mail Quadrant', 'MailQuadrant', 'Mail Quadrant', 'Character', '', 'MAIL_QUADRANT', 'Represents the quadrant of the city. (i.e. 100 Temple St NW) AKA post direction', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (328, 'Mail Apartment Unit Number', 'MailApartmentUnitNumber', 'Mail Apartment Unit Number', 'Character', '', 'MAIL_APARTMENT_UNIT_NUMBER', 'The unit or suite number of the mailing address', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (329, 'Mail City', 'MailCity', 'Mail City', 'Character', '', 'MAIL_CITY', 'The city associated with the mailing address', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (330, 'Mail State', 'MailState', 'Mail State', 'Character', '', 'MAIL_STATE', 'Two letter USPS abbreviation of the state', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (331, 'Mail Zipcode', 'MailZipcode', 'Mail Zipcode', 'Character', '', 'MAIL_ZIPCODE', 'Nine digit code assigned by the USPS', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (332, 'Mail Carrier Route', 'MailCarrierRoute', 'Mail Carrier Route', 'Character', '', 'MAIL_CARRIER_ROUTE', 'Four digit code used by the local mail carrier to identify delivery path', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (333, 'Batch Id', 'BatchId', 'Batch Id', 'Int', '', 'BATCH_ID', 'Batch number portion of Transaction ID', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (334, 'Batch Seq', 'BatchSeq', 'Batch Seq', 'Int', '', 'BATCH_SEQ', 'Sequence number portion of Transaction ID', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (335, 'Seller Last Name', 'SellerLastName', 'Seller Last Name', 'Character', '', 'SELLER_LAST_NAME', 'Last Name of Seller', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (336, 'Seller First Name', 'SellerFirstName', 'Seller First Name', 'Character', '', 'SELLER_FIRST_NAME', 'First Name of Seller', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (337, 'Seller Name Plaintiff 1', 'SellerNamePlaintiff1', 'Seller Name Plaintiff 1', 'Character', '', 'SELLER_NAME_PLAINTIFF_1', 'Full Name of First Seller', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (338, 'Seller Naem Plaintiff 2', 'SellerNaemPlaintiff2', 'Seller Naem Plaintiff 2', 'Character', '', 'SELLER_NAEM_PLAINTIFF_2', 'Full Name of Second Seller', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (339, 'Sale Code', 'SaleCode', 'Sale Code', 'Character', 'Lookup', 'SALES_TRANSACTION_TYPE_CODE', 'Field indicates what the financial consideration is (F=FULL, P= PARTIAL)', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (340, 'Sale Amount', 'SaleAmount', 'Sale Amount', 'Decimal', '', 'SALE_AMOUNT', 'Price of the sale appearing on the recording document', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (341, 'Sale Date', 'SaleDate', 'Sale Date', 'DateTime', '', 'SALE_DATE', 'Date the sale was legally completed', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (342, 'Recording Date', 'RecordingDate', 'Recording Date', 'DateTime', '', 'RECORDING_DATE', 'Date the transaction was recorded', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (343, 'Document Type Code', 'DocumentTypeCode', 'Document Type Code', 'Character', 'Lookup', 'DOCUMENT_TYPE', 'Type of transfer document recorded (Grand Deed, Trust Deed etc)', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (344, 'Transaction Type Code', 'TransactionTypeCode', 'Transaction Type Code', 'Character', 'Lookup', 'TRANSACTION_TYPE', 'FARES code identifying the type of transaction', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (345, 'Document Number', 'DocumentNumber', 'Document Number', 'Character', '', 'DOCUMENT_NUMBER', 'Recorders document number, used by some counties to record transactions', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (346, 'Book Page', 'BookPage', 'Book Page', 'Character', '', 'BOOK_PAGE', 'Recorders book & page, used by some counties to record transactions', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (347, 'Lender Last Name', 'LenderLastName', 'Lender Last Name', 'Character', '', 'LENDER_LAST_NAME', 'Name of Lender as recorded on the original document', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (348, 'Lender First Name', 'LenderFirstName', 'Lender First Name', 'Character', '', 'LENDER_FIRST_NAME', 'May be first name if lender is private party', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (349, 'Lender Address', 'LenderAddress', 'Lender Address', 'Character', '', 'LENDER_ADDRESS', 'Address of the Lender, as recorded on the original document', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (350, 'Lender City', 'LenderCity', 'Lender City', 'Character', '', 'LENDER_CITY', 'Lender City, as recorded on the original document', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (351, 'Lender State', 'LenderState', 'Lender State', 'Character', '', 'LENDER_STATE', 'Lender St, as recorded on the original document', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (352, 'Lender Zipcode', 'LenderZipcode', 'Lender Zipcode', 'Character', '', 'LENDER_ZIPCODE', 'Lender ZIP, as recorded on the original document', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (353, 'Lender Company Code', 'LenderCompanyCode', 'Lender Company Code', 'Int', '', 'LENDER_COMPANY_CODE', 'FARES internal code used to identify the Lender (no table is available)', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (354, 'Title Company Name', 'TitleCompanyName', 'Title Company Name', 'Character', '', 'TITLE_COMPANY_NAME', 'Filler', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (355, 'Title Company Code', 'TitleCompanyCode', 'Title Company Code', 'Int', '', 'TITLE_COMPANY_CODE', 'FARES internal code used to identify the Title Company associated with the sale', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (356, 'Mortgage Amount', 'MortgageAmount', 'Mortgage Amount', 'Int', '', 'MORTGAGE_AMOUNT', 'Amount of the mortgage', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (357, 'Mortgage Date', 'MortgageDate', 'Mortgage Date', 'Int', '', 'MORTGAGE_DATE', 'Date the mortgage was initiated', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (358, 'Mortgage Interest Rate', 'MortgageInterestRate', 'Mortgage Interest Rate', 'Decimal', '', 'MORTGAGE_INTEREST_RATE', 'Numeric Value of Interest Rate. i.e. "05.8750" Actual entry is 058750. End user must format field to place decimal point at second position', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (359, 'Mortgage Loan Type Code', 'MortgageLoanTypeCode', 'Mortgage Loan Type Code', 'Character', 'Lookup', 'MORTGAGE_LOAN_TYPE_CODE', 'Type of loan secured (VA, FHA, CONV etc)', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (360, 'Mortgage Deed Type Code', 'MortgageDeedTypeCode', 'Mortgage Deed Type Code', 'Character', 'Lookup', 'MORTGAGE_DEED_TYPE_CODE', 'Type of deed used for recording (Agreement of sale, Assumption Etc)', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (361, 'Mortgage Term Code', 'MortgageTermCode', 'Mortgage Term Code', 'Character', 'Lookup', 'MORTGAGE_TERM_CODE', 'Code used to identify whether number stored in Mortgage Term is days, months or years', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (362, 'Mortgage Term', 'MortgageTerm', 'Mortgage Term', 'Int', '', 'MORTGAGE_TERM', 'Length of time for the mortgage to mature', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (363, 'Mortgage Due Date', 'MortgageDueDate', 'Mortgage Due Date', 'DateTime', '', 'MORTGAGE_DUE_DATE', 'The date the mortgage becomes due', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (364, 'Mortgage Assumption Amount', 'MortgageAssumptionAmount', 'Mortgage Assumption Amount', 'Int', '', 'MORTGAGE_ASSUMPTION_AMOUNT', 'The assumption amount related to the existing mortgage', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (365, '2nd Mortgage Amount', '2ndMortgageAmount', '2nd Mortgage Amount', 'Decimal', '', '2ND_MORTGAGE_AMOUNT', 'Amount associated with a second mortgage', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (366, '2nd Mortgage Loan Type Code', '2ndMortgageLoanTypeCode', '2nd Mortgage Loan Type Code', 'Character', 'Lookup', 'MORTGAGE_LOAN_TYPE_CODE', 'Type of loan secured (VA, FHA, CONV etc)', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (367, '2nd Mortgage Deed Type Code', '2ndMortgageDeedTypeCode', '2nd Mortgage Deed Type Code', 'Character', 'Lookup', 'MORTGAGE_DEED_TYPE_CODE', 'Type of deed used for recording (Agreement of sale, Assumption etc)', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (368, 'Pri Cat Code', 'PriCatCode', 'Pri Cat Code', 'Character', 'Lookup', 'PRI_CAT_CODE', 'Primary category of the transaction type (i.e.: arms length)', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (369, 'Mtg Sec Cat Codes', 'MtgSecCatCodes', 'Mtg Sec Cat Codes', 'Character', 'Lookup', 'Sec_Cat_Code', 'Detailed category codes which provide additional mortgage information. See table', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (370, 'Deed Sec Cat Codes', 'DeedSecCatCodes', 'Deed Sec Cat Codes', 'Character', 'Lookup', 'Sec_Cat_Code', 'Detailed category codes which provide additional deed information. See table', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (371, 'Ownership Transfer Percentage', 'OwnershipTransferPercentage', 'Ownership Transfer Percentage', 'Int', '', 'OWNERSHIP_TRANSFER_PERCENTAGE', 'A percentile showing the percentage of ownership transferred', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (372, 'Universal Land Use Code', 'UniversalLandUseCode', 'Universal Land Use Code', 'Character', 'Lookup', 'UNIVERSAL_LAND_USE_CODE', 'FARES established Land Use code converted from individual county supplied codes.', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (373, 'Property Indicator Code', 'PropertyIndicatorCode', 'Property Indicator Code', 'Character', 'Lookup', 'PROPERTY_INDICATOR_CODE', 'FARES generated code to easily identify types of property (Residential, Commercial, Vacant etc)', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (374, 'Seller Carry Back Flag', 'SellerCarryBackFlag', 'Seller Carry Back Flag', 'Character', '', 'SELLER_CARRY_BACK_FLAG', 'Indicator showing the Seller carried the mortgage', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (375, 'Inter Family Flag', 'InterFamilyFlag', 'Inter Family Flag', 'Character', '', 'INTER_FAMILY_FLAG', 'Indicator showing the sale is inter-family', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (376, 'Private Party Lender Flag', 'PrivatePartyLenderFlag', 'Private Party Lender Flag', 'Character', '', 'PRIVATE_PARTY_LENDER_FLAG', 'Indicator showing the Lender is a Private Party', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (377, 'Mortgage Interest Rate Type Code', 'MortgageInterestRateTypeCode', 'Mortgage Interest Rate Type Code', 'Character', '', 'MORTGAGE_INTEREST_RATE_TYPE_CODE', 'Interest rate type of the loan (Adjustable, Fixed)', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (378, 'Construction Loan Flag', 'ConstructionLoanFlag', 'Construction Loan Flag', 'Character', '', 'CONSTRUCTION_LOAN_FLAG', 'Indicator showing the loan is for construction', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (379, 'Resale New Construction Code', 'ResaleNewConstructionCode', 'Resale New Construction Code', 'Character', '', 'RESALE_NEW_CONSTRUCTION_CODE', '"M" shows the sale is a re-sale, "N" shows the sale is for new construction', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (380, 'Forclosure Code', 'ForclosureCode', 'Forclosure Code', 'Character', '', 'FORCLOSURE_CODE', 'Indicator showing the transaction is a foreclosure', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (381, 'Cash Mortgage Purchase Code', 'CashMortgagePurchaseCode', 'Cash Mortgage Purchase Code', 'Character', '', 'CASH_MORTGAGE_PURCHASE_CODE', '"Q" indicates the sale was for cash, "R" indicates the sale was mortgaged', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (382, 'Equity Flag Code', 'EquityFlagCode', 'Equity Flag Code', 'Character', '', 'EQUITY_FLAG_CODE', 'Indicator showing the transaction is an equity loan', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (383, 'Refi Flag Code', 'RefiFlagCode', 'Refi Flag Code', 'Character', '', 'REFI_FLAG_CODE', 'Indicator showing the transaction is a re-finance', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (384, 'Residential Model Indicator Flag', 'ResidentialModelIndicatorFlag', 'Residential Model Indicator Flag', 'Character', '', 'RESIDENTIAL_MODEL_INDICATOR_FLAG', 'Indicator is set to indicate the property is residential based on zip code and value', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (385, 'Record Type Code', 'RecordTypeCode', 'Record Type Code', 'Character', '', 'RECORD_TYPE_CODE', 'Indicator showing if the record is a new tecord or a older record that has been changed:', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (386, 'Filler01', 'Filler01', 'Filler01', 'Character', '', 'FILLER01', 'FILLER', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (387, 'Filler02', 'Filler02', 'Filler02', 'Character', '', 'FILLER02', 'FILLER', 'CoreLogic', 'county', 'deed');
INSERT INTO config_data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (388, 'Filler03', 'Filler03', 'Filler03', 'Character', '', 'FILLER03', 'FILLER', 'CoreLogic', 'county', 'deed');


--
-- Name: config_data_source_fields_MetadataEntryID_seq; Type: SEQUENCE SET; Schema: public; Owner: dev
--

SELECT pg_catalog.setval('"config_data_source_fields_MetadataEntryID_seq"', 388, true);


--
-- PostgreSQL database dump complete
--

