CREATE TABLE SOME_TABLE_RENAME (
  id serial,
  auth_user_id int4 NOT NULL,
  rm_inserted_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now_utc(),
  rm_modified_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now_utc(),
  CONSTRAINT SOME_TABLE_RENAME_auth_user_id_fk FOREIGN KEY ("auth_user_id") REFERENCES auth_user ("id") ON UPDATE CASCADE ON DELETE CASCADE,
  PRIMARY KEY (id) NOT DEFERRABLE INITIALLY IMMEDIATE,
)
WITH (OIDS=FALSE);


CREATE TRIGGER update_modified_time_SOME_TABLE_RENAME
BEFORE UPDATE ON SOME_TABLE_RENAME
FOR EACH ROW EXECUTE PROCEDURE update_rm_modified_time_column();
