CREATE TABLE SOME_TABLE_RENAME (
	id serial,
	rm_inserted_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now_utc(),
	rm_modified_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now_utc(),
	PRIMARY KEY (id) NOT DEFERRABLE INITIALLY IMMEDIATE,
)
WITH (OIDS=FALSE);


CREATE TRIGGER update_modified_time_SOME_TABLE_RENAME
BEFORE UPDATE ON SOME_TABLE_RENAME
FOR EACH ROW EXECUTE PROCEDURE update_rm_modified_time_column();
