DROP TRIGGER IF EXISTS delete_modified_auth_m2m_user_mls_to_auth_user_mlses_verified
on auth_m2m_user_mls;

CREATE TRIGGER delete_modified_auth_m2m_user_mls_to_auth_user_mlses_verified
AFTER DELETE ON auth_m2m_user_mls
FOR EACH ROW EXECUTE PROCEDURE f_update_mlses_verified();

DROP TRIGGER IF EXISTS update_modified_auth_m2m_user_mls_to_auth_user_mlses_verified
on auth_m2m_user_mls;

CREATE TRIGGER update_modified_auth_m2m_user_mls_to_auth_user_mlses_verified
AFTER UPDATE ON auth_m2m_user_mls
FOR EACH ROW EXECUTE PROCEDURE f_update_mlses_verified();

DROP TRIGGER IF EXISTS insert_modified_auth_m2m_user_mls_to_auth_user_mlses_verified
on auth_m2m_user_mls;

CREATE TRIGGER insert_modified_auth_m2m_user_mls_to_auth_user_mlses_verified
AFTER INSERT ON auth_m2m_user_mls
FOR EACH ROW EXECUTE PROCEDURE f_update_mlses_verified();
