ALTER TABLE config_mls ADD COLUMN rm_inserted_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now_utc();
ALTER TABLE config_mls ADD COLUMN rm_modified_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now_utc();
