DROP TRIGGER IF EXISTS insert_modified_auth_m2m_user_locations_to_auth_user_fips_codes
on auth_m2m_user_locations;

CREATE TRIGGER insert_modified_auth_m2m_user_locations_to_auth_user_fips_codes
AFTER INSERT ON auth_m2m_user_locations
FOR EACH ROW EXECUTE PROCEDURE f_update_fips_codes();
