#!/bin/bash
set -e
set -o pipefail

SCRIPT_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null && pwd )/.."


source $SCRIPT_DIR/app/syncVars

if [[ "$IS_HEROKU" != "" ]]
then
    bin/start-pgbouncer-stunnel coffee $SCRIPT_DIR/../backend/masterWorker.coffee
else
    coffee $SCRIPT_DIR/../backend/masterWorker.coffee
fi
