#!/bin/bash
set -e

SCRIPT_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null && pwd )/.."


source $SCRIPT_DIR/app/syncVars
export JQ_QUEUE_NAME="$@"

if [[ "$IS_HEROKU" != "" ]]
then
    bin/start-pgbouncer-stunnel coffee $SCRIPT_DIR/../backend/jobQueueWorker.coffee "$@"
else
    coffee $SCRIPT_DIR/../backend/jobQueueWorker.coffee "$@"
fi
