#!/bin/bash
set -e

SCRIPT_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null && pwd )/.."


source $SCRIPT_DIR/app/syncVars
export JQ_QUEUE_NAME="$@"

if [[ "$IS_HEROKU" != "" ]]
then
    export PGBOUNCER_URLS="DATABASE_URL RAW_TEMP_DATABASE_URL"
    export PGBOUNCER_MAX_CLIENT_CONN=300
    export PGBOUNCER_DEFAULT_POOL_SIZE=15
    export PGBOUNCER_MIN_POOL_SIZE=2
    export PGBOUNCER_RESERVE_POOL_SIZE=0
    export PGBOUNCER_LOG_CONNECTIONS=0  # no
    export PGBOUNCER_LOG_DISCONNECTIONS=0  # no
    export PGBOUNCER_LOG_POOLER_ERRORS=1  # yes

    bin/start-pgbouncer-stunnel coffee $SCRIPT_DIR/../backend/jobQueueWorker.coffee "$@"
else
    coffee $SCRIPT_DIR/../backend/jobQueueWorker.coffee "$@"
fi
