#!/bin/bash
set -e

if [[ "$IS_DEBUG" == "true" ]]
then
    if [[ "$USE_DEBUG_PORT" == "" ]]
    then
        DEBUG_ARG="--debug"
    else
        DEBUG_ARG="--debug=$USE_DEBUG_PORT"
    fi

    echo "Start Gulp with $DEBUG_ARG"
fi

if [[ "$IS_HEROKU" == "" ]]
then
    DIR="$( cd -P "$( dirname "$0" )" > /dev/null && pwd )"
    cd "$DIR/../.."
else
    cd /app
fi


if [[ $PORT -eq 5000 ]]
then
  unset PORT
fi

if [[ "$IS_HEROKU" != "" ]]; then
  gulp $GULP_COLOR prod &
  if [[ "$DO_PERF" != "" ]]; then
    bin/start-pgbouncer-stunnel coffee --nodejs --perf-basic-prof ./backend/server.coffee
  else
    bin/start-pgbouncer-stunnel coffee ./backend/server.coffee
  fi
else
  gulp $GULP_COLOR $GULP_TARGET $DEBUG_ARG
fi
