#!/bin/bash
set -e

if [[ "$IS_HEROKU" == "" ]]
then
    DIR="$( cd -P "$( dirname "$0" )" > /dev/null && pwd )"
    cd "$DIR/../.."
fi


if [[ $PORT -eq 5000 ]]
then
  unset PORT
fi

if [[ "$IS_HEROKU" != "" ]]
then
  gulp prod
  coffee /app/backend/server.coffee
elif [[  "$BARE_EXPRESS_SERVER" != "" ]]
then
  gulp prod
  coffee ./backend/server.coffee
else
  gulp
fi
