#!/bin/bash
set -e
set -o pipefail

SCRIPT_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null && pwd )/.."
ORIG_DIR=`pwd`

# make sure we start in the app dir
cd $SCRIPT_DIR/..


$SCRIPT_DIR/database/syncDb main
$SCRIPT_DIR/database/syncDb normalized

coffee $SCRIPT_DIR/misc/syncEncryptionKey.coffee

$SCRIPT_DIR/app/serve


# reset cwd
cd $ORIG_DIR
