#!/bin/bash
set -e

SCRIPT_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null && pwd )/.."


if [[ "$IS_HEROKU" != "" ]]
then
  # this ensures we never wait more than 60 seconds before letting nginx bind the port;
  # we give 15s slack for heroku startup overhead, nginx startup, etc

  rm -f /tmp/app-initialized
  rm -f /tmp/nginx.socket
  
  (
    # this value is used in a calculation in nginx.conf.erb, so if it is changed here, that file should be changed too
    sleep 10
    echo "forcing early app init message..."
    touch /tmp/app-initialized
  ) &

  mkdir -p config
  bin/start-nginx $SCRIPT_DIR/app/startApp
else
  # not on heroku, so don't mess with nginx
  $SCRIPT_DIR/app/startApp
fi
