#!/bin/bash
set -e

SCRIPT_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null && pwd )/.."


$SCRIPT_DIR/app/stopServe

source $SCRIPT_DIR/app/syncVars

$SCRIPT_DIR/database/syncMainDb

coffee $SCRIPT_DIR/misc/syncEncryptionKey.coffee

$SCRIPT_DIR/app/serve
