#!/bin/bash
set -e
set -o pipefail



if [ -n "$IS_HEROKU" ] ; then
    echo "in Heroku, skipping stopServe script"
else


    DIR="$( cd -P "$( dirname "$0" )" > /dev/null && pwd )"
    cd "$DIR/.."


    if [[ $# == 0 ]]
    then
        PORTS="3000 4000"
    else
        PORTS="$*"
    fi

    for i in $PORTS
    do
        PID=$(./app/getRunningPID $i)
        if [[ -n $PID ]]; then
            kill $PID
            someThingWasKilled='true'
        else
            if [[ -z $someThingWasKilled ]];then
                echo "We're good, nothing running to stop."
            fi
        fi
    done

fi

