#!/bin/bash

SCRIPT_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null && pwd )/.."


LOCATION=""
if [[ "$APP_BASENAME" == "admin" ]]
then
    if [[ "$NODE_ENV" == "staging" ]]
    then
        LOCATION="@${INSTANCE_NAME}-realtymaps-map"
    elif [[ "$NODE_ENV" == "production" ]]
    then
        LOCATION="@realtymaps-map"
    fi
fi


eval "export MAIN_DATABASE_URL=`$SCRIPT_DIR/database/getDbUrl MAIN_DATABASE$LOCATION`"
eval "export RAW_TEMP_DATABASE_URL=`$SCRIPT_DIR/database/getDbUrl RAW_TEMP_DATABASE$LOCATION`"
