BEGIN;

DROP TABLE IF EXISTS temp_lookup_mls;

CREATE TABLE temp_lookup_mls (
  state_name varchar NOT NULL,
  full_name varchar NOT NULL,
	mls varchar,
  CONSTRAINT temp_lookup_mls_mult_unique UNIQUE (state_name, full_name, mls)
)
WITH (OIDS=FALSE);


INSERT INTO temp_lookup_mls VALUES ('AL', 'Baldwin County Association of Realtors', 'BCAR');
INSERT INTO temp_lookup_mls VALUES ('AL', 'Greater Alabama MLS', 'BARBHAM');
INSERT INTO temp_lookup_mls VALUES ('AL', 'Cullman Association of Realtors', 'CAR');
INSERT INTO temp_lookup_mls VALUES ('AL', 'Covington Association of Realtors', 'CBOR');
INSERT INTO temp_lookup_mls VALUES ('AL', 'Dothan Association of Realtors', 'DAR');
INSERT INTO temp_lookup_mls VALUES ('AL', 'Eufaula Board of REALTORS®', 'EBR');
INSERT INTO temp_lookup_mls VALUES ('AL', 'Emerald Coast Association of Realtors', 'ECAOR');
INSERT INTO temp_lookup_mls VALUES ('AL', 'Gulf Coast MLS', 'GCMLS');
INSERT INTO temp_lookup_mls VALUES ('AL', 'Lee County Association of Realtors', 'LCAR');
INSERT INTO temp_lookup_mls VALUES ('AL', 'Lake Martin Area Association of Realtors', 'LMAAR');
INSERT INTO temp_lookup_mls VALUES ('AL', 'Montgomery Area Association of Realtors MLS', 'MAAR');
INSERT INTO temp_lookup_mls VALUES ('AL', 'Monroe County Board of REALTORS®', 'MCBR');
INSERT INTO temp_lookup_mls VALUES ('AL', 'Phenix City Board of Realtors', 'PCAR');
INSERT INTO temp_lookup_mls VALUES ('AL', 'Shoals Area Association of Realtors', 'SHOALS');
INSERT INTO temp_lookup_mls VALUES ('AL', 'Walker County Area Board of REALTORS®', 'WBR');
INSERT INTO temp_lookup_mls VALUES ('AL', 'Wiregrass MLS ', 'WMLS');
INSERT INTO temp_lookup_mls VALUES ('AK', 'Alaska Multiple Listing Service', 'AMLS');
INSERT INTO temp_lookup_mls VALUES ('AK', 'Greater Fairbanks MLS ', 'GFBR');
INSERT INTO temp_lookup_mls VALUES ('AK', 'Southeast Alaska Board of Realtors ', null);
INSERT INTO temp_lookup_mls VALUES ('AZ', 'Southeast Arizona Multiple Listing Service', 'AEAZMLS');
INSERT INTO temp_lookup_mls VALUES ('AZ', 'Arizona Regional Multiple Listing Service, Inc.', 'ARMLS');
INSERT INTO temp_lookup_mls VALUES ('AZ', 'Fredonia MLS', 'FMLS');
INSERT INTO temp_lookup_mls VALUES ('AZ', 'Globe/Miami MLS', 'GMMLS');
INSERT INTO temp_lookup_mls VALUES ('AZ', 'Green Valley/Sahuarita Association of REALTORS®', 'GVAR');
INSERT INTO temp_lookup_mls VALUES ('AZ', 'Gila Valley MLS', 'GVMLS');
INSERT INTO temp_lookup_mls VALUES ('AZ', 'Northern Arizona Multiple Listing Service', 'NAMLS');
INSERT INTO temp_lookup_mls VALUES ('AZ', 'Northwest Arizona MLS', 'NWAMLS');
INSERT INTO temp_lookup_mls VALUES ('AZ', 'Prescott Area Association of Realtors®', 'PAAR');
INSERT INTO temp_lookup_mls VALUES ('AZ', 'Page Lake Powell MLS', 'PLPMLS');
INSERT INTO temp_lookup_mls VALUES ('AZ', 'Santa Cruz County Board of REALTORS®', 'SCCBR');
INSERT INTO temp_lookup_mls VALUES ('AZ', 'Sedona Verde Valley Association of Realtors', 'SVVAR');
INSERT INTO temp_lookup_mls VALUES ('AZ', 'Tucson Association of REALTORS ®, Inc.', 'TARMLS');
INSERT INTO temp_lookup_mls VALUES ('AZ', 'Western Arizona Realtors Data Exchange', 'WARDEX');
INSERT INTO temp_lookup_mls VALUES ('AZ', 'White Mountain Association of Realtors', 'WMAR');
INSERT INTO temp_lookup_mls VALUES ('AZ', 'Yuma Association of Realtors', 'YUMA');
INSERT INTO temp_lookup_mls VALUES ('AR', 'Northwest Arkansas Board of REALTORS®', 'ARMLS');
INSERT INTO temp_lookup_mls VALUES ('AR', 'Cooperative Arkansas Realtors Multiple Listing Service', 'CARMLS');
INSERT INTO temp_lookup_mls VALUES ('AR', 'Crittenden County Board of REALTORS', 'CCBR');
INSERT INTO temp_lookup_mls VALUES ('AR', 'Fort Smith Board of Realtors', 'FSBOR');
INSERT INTO temp_lookup_mls VALUES ('AR', 'Harrison District Board of REALTORS', 'HDBR');
INSERT INTO temp_lookup_mls VALUES ('AR', 'Hot Springs Board of Realtors', 'HSBRA');
INSERT INTO temp_lookup_mls VALUES ('AR', 'Jonesboro Board of Realtors', 'JBR');
INSERT INTO temp_lookup_mls VALUES ('AR', 'Memphis Area Association of Realtors®', 'MAAR');
INSERT INTO temp_lookup_mls VALUES ('AR', 'North Central Board of Realtors', 'NCBR');
INSERT INTO temp_lookup_mls VALUES ('AR', 'Russellville Board of Realtors', 'RBOR');
INSERT INTO temp_lookup_mls VALUES ('CA', 'Bay East, Contra Costa, EBRD', 'BEAR/CCAR/EBRD');
INSERT INTO temp_lookup_mls VALUES ('CA', 'Bakersfield Association of Realtors', 'BAOR');
INSERT INTO temp_lookup_mls VALUES ('CA', 'Bay Area Real Estate Information Services, Inc.', 'BAREIS');
INSERT INTO temp_lookup_mls VALUES ('CA', 'Big Bear Association of REALTORS', 'BBVBOR');
INSERT INTO temp_lookup_mls VALUES ('CA', 'Trinity County MLS', 'BVP');
INSERT INTO temp_lookup_mls VALUES ('CA', 'Calaveras County Association of Realtors', 'CCAR');
INSERT INTO temp_lookup_mls VALUES ('CA', 'Central Coast Regional Multiple Listing Service', 'CCRMLS');
INSERT INTO temp_lookup_mls VALUES ('CA', 'California Desert Association of REALTORS®, Inc.', 'CDAR');
INSERT INTO temp_lookup_mls VALUES ('CA', 'Combined LA Westside Multiple Listing Service, Inc', 'CLAW');
INSERT INTO temp_lookup_mls VALUES ('CA', 'Coastal Mendocino Association of Realtors', 'CMBAR');
INSERT INTO temp_lookup_mls VALUES ('CA', 'CRIS-Net Regional MLS (Southland)', 'CRISNET');
INSERT INTO temp_lookup_mls VALUES ('CA', 'Conejo Simi Moorpark Association of REALTORS', 'CSMAOR');
INSERT INTO temp_lookup_mls VALUES ('CA', 'Del Norte Association of Realtors', 'DNAOR');
INSERT INTO temp_lookup_mls VALUES ('CA', 'Fresno Association of Realtors', 'FAR');
INSERT INTO temp_lookup_mls VALUES ('CA', 'Greater Antelope Valley Association of Realtors', 'GAVAR');
INSERT INTO temp_lookup_mls VALUES ('CA', 'Humboldt Association of Realtors', 'HAR');
INSERT INTO temp_lookup_mls VALUES ('CA', 'Idyllwild Association of Realtors', 'IAR');
INSERT INTO temp_lookup_mls VALUES ('CA', 'Inyo County MLS', 'IMLS');
INSERT INTO temp_lookup_mls VALUES ('CA', 'I-Tech', 'ITECH');
INSERT INTO temp_lookup_mls VALUES ('CA', 'Imperial County Association of Realtors®', 'ICAOR');
INSERT INTO temp_lookup_mls VALUES ('CA', 'Kern River Lake Isabella Board Of Realtors', 'KRLIMLS');
INSERT INTO temp_lookup_mls VALUES ('CA', 'Lake County Association of REALTORS®', 'LCAOR');
INSERT INTO temp_lookup_mls VALUES ('CA', 'Lompoc Valley Association of Realtors', 'LVAR');
INSERT INTO temp_lookup_mls VALUES ('CA', 'Modoc County Listing Service', 'MCLS');
INSERT INTO temp_lookup_mls VALUES ('CA', 'Mammoth Lakes Board of REALTORS ®, Inc.', 'MLBOR');
INSERT INTO temp_lookup_mls VALUES ('CA', 'MLS Listings, Inc.', 'MLSListings');
INSERT INTO temp_lookup_mls VALUES ('CA', 'California Regional Multiple Listing Service, Inc', 'CRMLS');
INSERT INTO temp_lookup_mls VALUES ('CA', 'Orange Belt Board of Realtors', 'OBBR');
INSERT INTO temp_lookup_mls VALUES ('CA', 'Plumas Association of REALTORS', 'PMLS');
INSERT INTO temp_lookup_mls VALUES ('CA', 'Ridgecrest Area Association of Realtors', 'RAAR');
INSERT INTO temp_lookup_mls VALUES ('CA', 'Rim O'' The World Association of REALTORS', 'ROWAR');
INSERT INTO temp_lookup_mls VALUES ('CA', 'SANDICOR', 'SANDICOR');
INSERT INTO temp_lookup_mls VALUES ('CA', 'Siskiyou Association of Realtors', 'SAR');
INSERT INTO temp_lookup_mls VALUES ('CA', 'San Francisco Association of REALTORS', 'SFMLS');
INSERT INTO temp_lookup_mls VALUES ('CA', 'Shasta MLS', 'SHASTA');
INSERT INTO temp_lookup_mls VALUES ('CA', 'Southern California Multiple Listing Service', 'SoCal MLS');
INSERT INTO temp_lookup_mls VALUES ('CA', 'South Tahoe Association of REALTORS®', 'STAOR');
INSERT INTO temp_lookup_mls VALUES ('CA', 'Tehachapi Area Association of Realtors', 'TAARCA');
INSERT INTO temp_lookup_mls VALUES ('CA', 'Tehama County Association Of Realtors', 'TCAOR');
INSERT INTO temp_lookup_mls VALUES ('CA', 'Tuolumne County Association of Realtors', 'TCAR');
INSERT INTO temp_lookup_mls VALUES ('CA', 'Tulare County MLS', 'TCMLS');
INSERT INTO temp_lookup_mls VALUES ('CA', 'Tahoe Sierra Board of Realtors®', 'TSBOR');
INSERT INTO temp_lookup_mls VALUES ('CA', 'Ventura County Coastal Association of REALTORS®', 'VCMLS');
INSERT INTO temp_lookup_mls VALUES ('CA', 'High Desert Association of REALTORS®', 'VVMLS');
INSERT INTO temp_lookup_mls VALUES ('CO', 'Aspen/Glenwood Springs MLS', 'AGSMLS');
INSERT INTO temp_lookup_mls VALUES ('CO', 'Realtors of Central Colorado Inc.', 'CCBR');
INSERT INTO temp_lookup_mls VALUES ('CO', 'Chaffee County MLS ', 'CCBMLS');
INSERT INTO temp_lookup_mls VALUES ('CO', 'Colorado Real Estate Network ', 'CREN');
INSERT INTO temp_lookup_mls VALUES ('CO', 'Grand County MLS ', 'GRNCMLS');
INSERT INTO temp_lookup_mls VALUES ('CO', 'Grand Junction MLS ', 'GJMLS');
INSERT INTO temp_lookup_mls VALUES ('CO', 'Gunnison Country MLS ', 'GCMLS');
INSERT INTO temp_lookup_mls VALUES ('CO', 'Information and Real Estate Services ', 'IRES');
INSERT INTO temp_lookup_mls VALUES ('CO', 'Metrolist Inc., DBA ReColorado ', 'MTOMLS');
INSERT INTO temp_lookup_mls VALUES ('CO', 'Pikes Peak MLS ', 'PPAR');
INSERT INTO temp_lookup_mls VALUES ('CO', 'Pueblo MLS ', 'PARMLS');
INSERT INTO temp_lookup_mls VALUES ('CO', 'Steamboat Springs MLS ', 'SSBRMLS');
INSERT INTO temp_lookup_mls VALUES ('CO', 'Summit County MLS ', 'SARMLS');
INSERT INTO temp_lookup_mls VALUES ('CO', 'Telluride MLS ', 'TRIDEMLS');
INSERT INTO temp_lookup_mls VALUES ('CO', 'Vail Multi List ', 'VBRMLS');
INSERT INTO temp_lookup_mls VALUES ('CO', 'Westcliffe MLS ', 'WMLS');
INSERT INTO temp_lookup_mls VALUES ('CT', 'Coastal Association MLS ', 'CAMLS');
INSERT INTO temp_lookup_mls VALUES ('CT', 'Connecticut Statewide MLS', 'CT-STATEWIDE');
INSERT INTO temp_lookup_mls VALUES ('CT', 'Consolidated MLS ', 'CMLS');
INSERT INTO temp_lookup_mls VALUES ('CT', 'Greenwich MLS ', 'GRWMLS');
INSERT INTO temp_lookup_mls VALUES ('DE', 'Sussex County Delaware MLS ', 'DELMLS');
INSERT INTO temp_lookup_mls VALUES ('DE', 'Trend MLS ', 'TREND');
INSERT INTO temp_lookup_mls VALUES ('FL', 'Bay County Realtors Association', 'BCAR');
INSERT INTO temp_lookup_mls VALUES ('FL', 'Bonita Springs Estero Association of Realtors', 'BEAR');
INSERT INTO temp_lookup_mls VALUES ('FL', 'Chipola Area Board of Realtors, Inc.', 'CABR');
INSERT INTO temp_lookup_mls VALUES ('FL', 'Cape Coral Association of Realtors', 'CCMLS');
INSERT INTO temp_lookup_mls VALUES ('FL', 'Central Listing Service at Ocean Reef', 'CLSOR');
INSERT INTO temp_lookup_mls VALUES ('FL', 'Daytona Beach Area Association of Realtors', 'DBAAR');
INSERT INTO temp_lookup_mls VALUES ('FL', 'Dixie-Gilchrist-Levy Multiple Listing Service', 'DGLMLS');
INSERT INTO temp_lookup_mls VALUES ('FL', 'Emerald Coast Association of Realtors', 'ECAOR');
INSERT INTO temp_lookup_mls VALUES ('FL', 'Flagler County Association of Realtors', 'FLGMLS');
INSERT INTO temp_lookup_mls VALUES ('FL', 'Florida Keys Board of REALTORS®', 'FLKEYSMLSFL');
INSERT INTO temp_lookup_mls VALUES ('FL', 'REALTOR® Association of Greater Fort Myers and the Beaches, Inc.', 'SWFL');
INSERT INTO temp_lookup_mls VALUES ('FL', 'Gainesville MLS', 'GMLS');
INSERT INTO temp_lookup_mls VALUES ('FL', 'Hernando County Association of REALTORS®, Inc.', 'HERNANDO');
INSERT INTO temp_lookup_mls VALUES ('FL', 'Heartland Multiple Listing Service, Inc.', 'HMLS');
INSERT INTO temp_lookup_mls VALUES ('FL', 'Key West Association of Realtors', 'KWAR');
INSERT INTO temp_lookup_mls VALUES ('FL', 'MIAMI Association of REALTORS®', 'MAOR');
INSERT INTO temp_lookup_mls VALUES ('FL', 'My Florida Regional Multiple Listing Service, Inc.', 'MFRMLS');
INSERT INTO temp_lookup_mls VALUES ('FL', 'Marco Island Area Association of Realtors', 'MIAAOR');
INSERT INTO temp_lookup_mls VALUES ('FL', 'Marathon and Lower Keys Association of Realtors', 'MLKAR');
INSERT INTO temp_lookup_mls VALUES ('FL', 'Naples Area Board of REALTORS', 'NABOR');
INSERT INTO temp_lookup_mls VALUES ('FL', 'Northeast Florida Multiple Listing Service, Inc.', 'NEFMLS');
INSERT INTO temp_lookup_mls VALUES ('FL', 'North Florida MLS', 'NFLMLS');
INSERT INTO temp_lookup_mls VALUES ('FL', 'New Smyrna Beach Board of Realtors', 'NSBBOR');
INSERT INTO temp_lookup_mls VALUES ('FL', 'Navarre Area Board of Realtors', 'NVABOR');
INSERT INTO temp_lookup_mls VALUES ('FL', 'Ocala/Marion County Association of REALTORS®', 'OMCARFL');
INSERT INTO temp_lookup_mls VALUES ('FL', 'Pensacola Association of REALTORS', 'PAR');
INSERT INTO temp_lookup_mls VALUES ('FL', 'Pinellas Suncoast Association of REALTORS®, Inc.', 'PINEALLAS');
INSERT INTO temp_lookup_mls VALUES ('FL', 'REALTORS Association of Citrus County, Inc.', 'RACC');
INSERT INTO temp_lookup_mls VALUES ('FL', 'Greater Fort Lauderdale Realtors', 'RAGFL');
INSERT INTO temp_lookup_mls VALUES ('FL', 'Realtors Association of Indian River County', 'RAIRC');
INSERT INTO temp_lookup_mls VALUES ('FL', 'Realtor® Association of Franklin & Gulf Counties', 'RAFGC');
INSERT INTO temp_lookup_mls VALUES ('FL', 'Realtor Association of Martin County', 'RAMC');
INSERT INTO temp_lookup_mls VALUES ('FL', 'Regional Multiple Listing Service, Inc.', 'RMLS-FL');
INSERT INTO temp_lookup_mls VALUES ('FL', 'South Broward Board of REALTORS®', 'SBBOR');
INSERT INTO temp_lookup_mls VALUES ('FL', 'Southwest Florida MLS', 'SWFMLS');
INSERT INTO temp_lookup_mls VALUES ('FL', 'Space Coast Association of Realtors', 'SCAOR');
INSERT INTO temp_lookup_mls VALUES ('FL', 'St. Augustine & St. John''s County Board of Realtors', 'SJCBOR');
INSERT INTO temp_lookup_mls VALUES ('FL', 'Tallahassee Board of Realtors', 'TBR');
INSERT INTO temp_lookup_mls VALUES ('FL', 'West Pasco Board of Realtors', 'WPBOR');
INSERT INTO temp_lookup_mls VALUES ('GA', 'Athens Area Association of Realtors', 'AAAR');
INSERT INTO temp_lookup_mls VALUES ('GA', 'Altamaha Basin Board of Realtors', 'ABBR');
INSERT INTO temp_lookup_mls VALUES ('GA', 'Americus Board of Realtors', 'ABOR');
INSERT INTO temp_lookup_mls VALUES ('GA', 'Albany Board of Realtors and Southwest Georgia MLS', 'AMLS');
INSERT INTO temp_lookup_mls VALUES ('GA', 'Crisp Area Board of Realtors', 'CABR');
INSERT INTO temp_lookup_mls VALUES ('GA', 'Greater Chattanooga Association of REALTORS', 'CARTN');
INSERT INTO temp_lookup_mls VALUES ('GA', 'Columbus Board of Realtors (GA)', 'CBOR');
INSERT INTO temp_lookup_mls VALUES ('GA', 'Central Georgia MLS', 'CGMLS');
INSERT INTO temp_lookup_mls VALUES ('GA', 'Douglas Coffee County Board of Realtors', 'DCCRB');
INSERT INTO temp_lookup_mls VALUES ('GA', 'Dalton MLS', 'DMI');
INSERT INTO temp_lookup_mls VALUES ('GA', 'First Multiple Listing Service, Inc.', 'FMLS');
INSERT INTO temp_lookup_mls VALUES ('GA', 'Greater Augusta Association of Realtors', 'GAAR');
INSERT INTO temp_lookup_mls VALUES ('GA', 'Georgia Multiple Listing Service', 'GAMLS');
INSERT INTO temp_lookup_mls VALUES ('GA', 'Golden Isles Association of REALTORS', 'GIAOR');
INSERT INTO temp_lookup_mls VALUES ('GA', 'Hinesville Board of Realtors', 'HABR');
INSERT INTO temp_lookup_mls VALUES ('GA', 'Lake Country Board of Realtors, Inc (GA)', 'LCBOR');
INSERT INTO temp_lookup_mls VALUES ('GA', 'Moultrie Board of Realtors', 'MBOR');
INSERT INTO temp_lookup_mls VALUES ('GA', 'MIDDLE GEORGIA MLS', 'MGAMLS');
INSERT INTO temp_lookup_mls VALUES ('GA', 'Milledgeville MLS', 'MMLS');
INSERT INTO temp_lookup_mls VALUES ('GA', 'Northeast Georgia Board of Realtors', 'NEGBOR');
INSERT INTO temp_lookup_mls VALUES ('GA', 'Savannah Board of Realtors', 'SBOR');
INSERT INTO temp_lookup_mls VALUES ('GA', 'Southeast Georgia Board of Realtors', 'SEGAMLS');
INSERT INTO temp_lookup_mls VALUES ('GA', 'Southwest Georgia Board of Realtors MLS', 'SWGA');
INSERT INTO temp_lookup_mls VALUES ('GA', 'Thomasville Area Board of Realtors', 'TABOR');
INSERT INTO temp_lookup_mls VALUES ('GA', 'Tift Area Board of Realtors', 'TBR');
INSERT INTO temp_lookup_mls VALUES ('GA', 'South Georgia MLS (Valdosta)', 'VMLS');
INSERT INTO temp_lookup_mls VALUES ('GA', 'West Metro Board of Realtors', 'WMBR');
INSERT INTO temp_lookup_mls VALUES ('HI', 'Honolulu Board of REALTORS®', 'HICENTRAL');
INSERT INTO temp_lookup_mls VALUES ('HI', 'Hawaii Information Service', 'HIS');
INSERT INTO temp_lookup_mls VALUES ('HI', 'Realtors ® Association of Maui, Inc.', 'RAM');
INSERT INTO temp_lookup_mls VALUES ('ID', 'Intermountain Multiple Listing Service', 'IMLS');
INSERT INTO temp_lookup_mls VALUES ('IL', 'Capital Area Association of REALTORS®', 'CAAR');
INSERT INTO temp_lookup_mls VALUES ('IL', 'Champaign County Association of Realtors', 'CCAR');
INSERT INTO temp_lookup_mls VALUES ('IL', 'Danville Area Board of Realtors', 'DABR');
INSERT INTO temp_lookup_mls VALUES ('IL', 'Egyptian Board of REALTORS ®, Inc', 'EBOR');
INSERT INTO temp_lookup_mls VALUES ('IL', 'Logan County Board of Realtors', 'LCBR');
INSERT INTO temp_lookup_mls VALUES ('IL', 'Mid America Regional Information Systems, Inc.', 'MARIS');
INSERT INTO temp_lookup_mls VALUES ('IL', 'Midwest Real Estate Data, LLC', 'MRED');
INSERT INTO temp_lookup_mls VALUES ('IL', 'Peoria Area Association of REALTORS®', 'PAAR');
INSERT INTO temp_lookup_mls VALUES ('IL', 'Peoria Area Association of REALTORS Commercial', 'PAARCOM');
INSERT INTO temp_lookup_mls VALUES ('IL', 'Quad Cities Area REALTORS® Association', 'QCARA');
INSERT INTO temp_lookup_mls VALUES ('IL', 'Rockford Area MLS', 'RAAR');
INSERT INTO temp_lookup_mls VALUES ('IL', 'Realtor Association of Northwestern Illinois', 'RANWI');
INSERT INTO temp_lookup_mls VALUES ('IL', 'Southwestern Illinois Regional MLS, Inc.', 'SIRMLS');
INSERT INTO temp_lookup_mls VALUES ('IN', 'Bedford Board of Realtors', 'BBOR');
INSERT INTO temp_lookup_mls VALUES ('IN', 'Bloomington MLS, Inc.', 'BMLS');
INSERT INTO temp_lookup_mls VALUES ('IN', 'MLS of Greater Cincinnati, Inc.', 'CincyMLS');
INSERT INTO temp_lookup_mls VALUES ('IN', 'Elkhart County Board of Realtors', 'ECBOR');
INSERT INTO temp_lookup_mls VALUES ('IN', 'Upstate Alliance of REALTORS® Multiple Listing Service, Inc.', 'UARMLSIN');
INSERT INTO temp_lookup_mls VALUES ('IN', 'Greater Northwest Indiana Association of REALTORS', 'GNIAR');
INSERT INTO temp_lookup_mls VALUES ('IN', 'Greater South Bend-Mishawaka Association of Realtors', 'GSBMAR');
INSERT INTO temp_lookup_mls VALUES ('IN', 'Kosciusko Board of Realtors MLS', 'KBOR');
INSERT INTO temp_lookup_mls VALUES ('IN', 'Lafayette Regional Association of REALTORS®', 'LRAOR');
INSERT INTO temp_lookup_mls VALUES ('IN', 'Mid-Eastern Indiana Association of Realtor MLS', 'MEINAR');
INSERT INTO temp_lookup_mls VALUES ('IN', 'MIBOR Service Corporation', 'MIBOR');
INSERT INTO temp_lookup_mls VALUES ('IN', 'Northeastern Indiana Association of Realtors', 'NEINAR');
INSERT INTO temp_lookup_mls VALUES ('IN', 'Southeastern Indiana Board of Realtors', 'SEIBR');
INSERT INTO temp_lookup_mls VALUES ('IN', 'Southern Indiana REALTORS Association', 'SIREA');
INSERT INTO temp_lookup_mls VALUES ('IN', 'Southwest Indiana Association of Realtors', 'SWAOR');
INSERT INTO temp_lookup_mls VALUES ('IN', 'Terre Haute Area Association of Realtors', 'THAAR');
INSERT INTO temp_lookup_mls VALUES ('IN', 'White County Association of Realtors', 'WCAR');
INSERT INTO temp_lookup_mls VALUES ('IA', 'Benton County Multiple Listing Service', 'BCMLS');
INSERT INTO temp_lookup_mls VALUES ('IA', 'Central Iowa Board of Realtors, Inc.', 'CIBOR');
INSERT INTO temp_lookup_mls VALUES ('IA', 'Clear Lake Board of Realtors', 'CLAK');
INSERT INTO temp_lookup_mls VALUES ('IA', 'Cedar Rapids Area Association of REALTORS®', 'CRAAR');
INSERT INTO temp_lookup_mls VALUES ('IA', 'Des Moines Area Association of REALTORS®, Inc.', 'DMAARIA');
INSERT INTO temp_lookup_mls VALUES ('IA', 'East Central Iowa Association of Realtors', 'ECIAOR');
INSERT INTO temp_lookup_mls VALUES ('IA', 'Fort Dodge Board of Realtors', 'FDBOR');
INSERT INTO temp_lookup_mls VALUES ('IA', 'Fairfield Iowa MLS', 'FFMLSIA');
INSERT INTO temp_lookup_mls VALUES ('IA', 'Fort Madison Multiple Listing Service', 'FMMLSIA');
INSERT INTO temp_lookup_mls VALUES ('IA', 'West Central Iowa MLS', 'WCIMLS');
INSERT INTO temp_lookup_mls VALUES ('IA', 'Greater Mason City Board of Realtors', 'GMC');
INSERT INTO temp_lookup_mls VALUES ('IA', 'Humboldt County MLS', 'HCMLSIA');
INSERT INTO temp_lookup_mls VALUES ('IA', 'Heart of Iowa MLS', 'HIAMLS');
INSERT INTO temp_lookup_mls VALUES ('IA', 'Iowa City Area Association of REALTORS®', 'ICAAR');
INSERT INTO temp_lookup_mls VALUES ('IA', 'Iowa Great Lakes Board of Realtors', 'IGLBOR');
INSERT INTO temp_lookup_mls VALUES ('IA', 'Keokuk MLS', 'KAMLS');
INSERT INTO temp_lookup_mls VALUES ('IA', 'Marshalltown Board MLS', 'MBORMLS');
INSERT INTO temp_lookup_mls VALUES ('IA', 'Mount Pleasant Area MLS', 'MPAMLS');
INSERT INTO temp_lookup_mls VALUES ('IA', 'Newton Board of REALTORS', 'NBRIA');
INSERT INTO temp_lookup_mls VALUES ('IA', 'North Central Iowa Board of Realtors', 'NCIAMLS');
INSERT INTO temp_lookup_mls VALUES ('IA', 'Northwest Iowa MLS', 'NWIAMLS');
INSERT INTO temp_lookup_mls VALUES ('IA', 'Oskaloosa Multiple Listing Service', 'OMLS');
INSERT INTO temp_lookup_mls VALUES ('IA', 'Plymouth County MLS', 'Plymouth County');
INSERT INTO temp_lookup_mls VALUES ('IA', 'Poweshiek County MLS', 'PCMLS');
INSERT INTO temp_lookup_mls VALUES ('IA', 'Quad Cities Area REALTORS® Association', 'QCARA');
INSERT INTO temp_lookup_mls VALUES ('IA', 'Rathbun Area Multiple Listing Service', 'RATHBUN');
INSERT INTO temp_lookup_mls VALUES ('IA', 'RLI Farm & Ranch Multiple Listing Service', 'RLIFARMRANCH');
INSERT INTO temp_lookup_mls VALUES ('IA', 'Storm Lake MLS', 'SLMLS');
INSERT INTO temp_lookup_mls VALUES ('IA', 'Southwest Iowa Association of Realtors', 'SWIAR');
INSERT INTO temp_lookup_mls VALUES ('IA', 'Tama MLS IA', 'TCMLS');
INSERT INTO temp_lookup_mls VALUES ('IA', 'Washington Iowa MLS', 'WAIAMLS');
INSERT INTO temp_lookup_mls VALUES ('IA', 'Northeast Iowa Regional Board of Realtors', 'WCFBOR');
INSERT INTO temp_lookup_mls VALUES ('IA', 'Webster City MLS', 'WCMLS');
INSERT INTO temp_lookup_mls VALUES ('KS', 'Emporia Multiple Listing Service', 'EMLSKS');
INSERT INTO temp_lookup_mls VALUES ('KS', 'Garden City Board of Realtors', 'GCBOR');
INSERT INTO temp_lookup_mls VALUES ('KS', 'Goodland Kansas Multiple Listing Service', 'GKSMLS');
INSERT INTO temp_lookup_mls VALUES ('KS', 'Hays Multiple Listing Service', 'HAYSMLS');
INSERT INTO temp_lookup_mls VALUES ('KS', 'Mid-Kansas MLS', 'PRAIRIE LAND ');
INSERT INTO temp_lookup_mls VALUES ('KS', 'Heartland Multiple Listing Service', 'HMLS');
INSERT INTO temp_lookup_mls VALUES ('KS', 'Lawrence Board of Realtors', 'LBOR');
INSERT INTO temp_lookup_mls VALUES ('KS', 'Manhattan Association of Realtors ', 'MAR');
INSERT INTO temp_lookup_mls VALUES ('KS', 'Parsons Kansas Area Multiple Listing Service', 'PKAMLS');
INSERT INTO temp_lookup_mls VALUES ('KS', 'Salina Multiple Listing Service', 'SMLS');
INSERT INTO temp_lookup_mls VALUES ('KS', 'Realtors of South Central Kansas Inc.', 'WAAR');
INSERT INTO temp_lookup_mls VALUES ('KS', 'Southeast Kansas Multiple Listing System', 'SEKMLS');
INSERT INTO temp_lookup_mls VALUES ('KS', 'Southwest Kansas Multiple Listing Service', 'SWKMLS');
INSERT INTO temp_lookup_mls VALUES ('KS', 'Sunflower Association of REALTORS®, Inc.', 'Topeka');
INSERT INTO temp_lookup_mls VALUES ('KY', 'Central Kentucky Association of Realtors', 'CKAR');
INSERT INTO temp_lookup_mls VALUES ('KY', 'Greater Louisville Association of REALTORS®', 'GLAR');
INSERT INTO temp_lookup_mls VALUES ('KY', 'Henderson Audubon Board of Realtors', 'HABR');
INSERT INTO temp_lookup_mls VALUES ('KY', 'Hopkinsville Christian & Todd County Association of Realtors', 'HCCBR');
INSERT INTO temp_lookup_mls VALUES ('KY', 'Heart of Kentucky Association of Realtors', 'HKYAR');
INSERT INTO temp_lookup_mls VALUES ('KY', 'Lexington-Bluegrass Association of Realtors', 'LBAR');
INSERT INTO temp_lookup_mls VALUES ('KY', 'Madison County Board of Realtors', 'MCBR');
INSERT INTO temp_lookup_mls VALUES ('KY', 'Madisonville-Hopkins County Board of Realtors', 'MHCBR');
INSERT INTO temp_lookup_mls VALUES ('KY', 'Northern Kentucky Association of REALTORS', 'NKAR');
INSERT INTO temp_lookup_mls VALUES ('KY', 'Greater Owensboro Realtor® Association', 'OMLS');
INSERT INTO temp_lookup_mls VALUES ('KY', 'REALTOR® Association of Southern Kentucky, Inc.', 'RASK');
INSERT INTO temp_lookup_mls VALUES ('KY', 'South Central Kentucky Association of Realtors', 'SCKAOR');
INSERT INTO temp_lookup_mls VALUES ('KY', 'Somerset-Lake Cumberland Board of Realtors', 'SLCBR');
INSERT INTO temp_lookup_mls VALUES ('KY', 'Western Kentucky Regional MLS Inc', 'WKYRMLS');
INSERT INTO temp_lookup_mls VALUES ('LA', 'Bayou Board of Realtors', 'BBOR');
INSERT INTO temp_lookup_mls VALUES ('LA', 'Northwest Louisiana Association of Realtors', 'NWLAM');
INSERT INTO temp_lookup_mls VALUES ('LA', 'New Orleans Metropolitan Board of Realtors', 'NOMAR');
INSERT INTO temp_lookup_mls VALUES ('LA', 'Greater Baton Rouge Board of Realtors', 'GBRAR');
INSERT INTO temp_lookup_mls VALUES ('LA', 'Central Louisiana Realtor Association', 'CLRA');
INSERT INTO temp_lookup_mls VALUES ('ME', 'Maine Real Estate Information System, Inc.', 'MREIS');
INSERT INTO temp_lookup_mls VALUES ('ME', 'Northern New England Real Estate Network', 'NNEREN');
INSERT INTO temp_lookup_mls VALUES ('MD', 'Coastal Association of Realtors MLS', 'CARMLS');
INSERT INTO temp_lookup_mls VALUES ('MD', 'Metropolitan Regional Information Systems, Inc.', 'MRIS');
INSERT INTO temp_lookup_mls VALUES ('MA', 'Berkshire County Board of Realtors', 'BCBOR');
INSERT INTO temp_lookup_mls VALUES ('MA', 'Cape Cod & Islands Association of REALTORS®, Inc.', 'CCIAOR');
INSERT INTO temp_lookup_mls VALUES ('MA', 'Northern New England Real Estate Network', 'NNEREN');
INSERT INTO temp_lookup_mls VALUES ('MI', 'Ann Arbor Area Board of Realtors®', 'AAABOR');
INSERT INTO temp_lookup_mls VALUES ('MI', 'Battle Creek Area Association of Realtors', 'BCAAR');
INSERT INTO temp_lookup_mls VALUES ('MI', 'Bay County Realtors Association', 'BCRA');
INSERT INTO temp_lookup_mls VALUES ('MI', 'Branch County Association of Realtors', 'BCAR');
INSERT INTO temp_lookup_mls VALUES ('MI', 'Clare Gladwin Board of REALTORS', 'CGBR');
INSERT INTO temp_lookup_mls VALUES ('MI', 'Down River Association of REALTORS® and Multiple Listing Service', 'Down River Assoc.');
INSERT INTO temp_lookup_mls VALUES ('MI', 'Eastern Upper Peninsula Board of REALTORS', 'EUPBR');
INSERT INTO temp_lookup_mls VALUES ('MI', 'East Central Association of REALTORS®', 'FAAR');
INSERT INTO temp_lookup_mls VALUES ('MI', 'Greater Kalamazoo Association of Realtors', 'GKAOR');
INSERT INTO temp_lookup_mls VALUES ('MI', 'Greater Lansing Association of Realtors', 'GLAR');
INSERT INTO temp_lookup_mls VALUES ('MI', 'Grand Rapids Association of REALTORS®', 'GRAR');
INSERT INTO temp_lookup_mls VALUES ('MI', 'Hillsdale County Board of Realtors', 'HCBOR');
INSERT INTO temp_lookup_mls VALUES ('MI', 'Jackson Multiple Listing Service, Inc.', 'JMLS');
INSERT INTO temp_lookup_mls VALUES ('MI', 'Lenawee County Association of REALTORS®', 'LCAR');
INSERT INTO temp_lookup_mls VALUES ('MI', 'Monroe County Association of Realtors®', 'MCAR');
INSERT INTO temp_lookup_mls VALUES ('MI', 'Multiple Listing Service MiRealSource', 'MiRealSource');
INSERT INTO temp_lookup_mls VALUES ('MI', 'Mason-Oceana Manistee Board of Realtors', 'MOMBR');
INSERT INTO temp_lookup_mls VALUES ('MI', 'Northern Michigan MLS', 'NMIMLS');
INSERT INTO temp_lookup_mls VALUES ('MI', 'Paul Bunyan Board of REALTORS', 'PBBR');
INSERT INTO temp_lookup_mls VALUES ('MI', 'Realcomp Limited II', 'REALCOMP');
INSERT INTO temp_lookup_mls VALUES ('MI', 'Saginaw Board of Realtors MLS', 'SBR');
INSERT INTO temp_lookup_mls VALUES ('MI', 'St. Joseph County Association of Realtors', 'SJCAR');
INSERT INTO temp_lookup_mls VALUES ('MI', 'Greater Shiawassee Regional Board of Realtors', 'SRBR');
INSERT INTO temp_lookup_mls VALUES ('MI', 'Southwestern Michigan Association of Realtors', 'SWMAR');
INSERT INTO temp_lookup_mls VALUES ('MI', 'Northern Great Lakes Realtors MLS', 'TAAR');
INSERT INTO temp_lookup_mls VALUES ('MI', 'Upper Peninsula Association of Realtors', 'UPAR');
INSERT INTO temp_lookup_mls VALUES ('MI', 'West Central Association of Realtors', 'WCAR');
INSERT INTO temp_lookup_mls VALUES ('MI', 'West Michigan Lakeshore Association of Realtors', 'WMLAR');
INSERT INTO temp_lookup_mls VALUES ('MI', 'Water Wonderland Board of Realtors®', 'WWMLS');
INSERT INTO temp_lookup_mls VALUES ('MN', 'Duluth Area Association of REALTORS®, Inc.', 'DAAR');
INSERT INTO temp_lookup_mls VALUES ('MN', 'Greater Alexandria Area MLS', 'GAAMLS');
INSERT INTO temp_lookup_mls VALUES ('MN', 'Greater Lakes Association of Realtors', 'GLAR');
INSERT INTO temp_lookup_mls VALUES ('MN', 'Itasca County Board of REALTORS', 'ICBR');
INSERT INTO temp_lookup_mls VALUES ('MN', 'Lake Region Association of REALTORS', 'LRMLS');
INSERT INTO temp_lookup_mls VALUES ('MN', 'Realtor Association of Southern Minnesota', 'RASM');
INSERT INTO temp_lookup_mls VALUES ('MN', 'Regional Multiple Listing Service of Minnesota [NorthStarMLS]', 'RMLS-MN');
INSERT INTO temp_lookup_mls VALUES ('MN', 'Superior Area Association of REALTORS®, Inc.', 'SAAR');
INSERT INTO temp_lookup_mls VALUES ('MN', 'Southeast Minnesota Association of REALTORS®', 'SEMAR');
INSERT INTO temp_lookup_mls VALUES ('MN', 'West Central Association of Realtors - MN', 'WCAR');
INSERT INTO temp_lookup_mls VALUES ('MS', 'Golden Triangle Association of Realtors', 'GTAR');
INSERT INTO temp_lookup_mls VALUES ('MS', 'Greenwood Board of Realtors', 'GWBR');
INSERT INTO temp_lookup_mls VALUES ('MS', 'Hattiesburg Area Association of Realtors', 'HAARMS');
INSERT INTO temp_lookup_mls VALUES ('MS', 'Laurel Board of Realtors', 'LBR');
INSERT INTO temp_lookup_mls VALUES ('MS', 'Memphis Area Association of Realtors®', 'MAAR');
INSERT INTO temp_lookup_mls VALUES ('MS', 'Mississippi Gulf Coast Multiple Listing Service, Inc.', 'MGCMLS');
INSERT INTO temp_lookup_mls VALUES ('MS', 'Central Mississippi MLS', 'CMR');
INSERT INTO temp_lookup_mls VALUES ('MS', 'Natchez Board of Realtors', 'NBR');
INSERT INTO temp_lookup_mls VALUES ('MS', 'North Central Mississippi Realtors', 'NCMR');
INSERT INTO temp_lookup_mls VALUES ('MS', 'Northeast Mississippi Board of Realtors', 'NEMSBD');
INSERT INTO temp_lookup_mls VALUES ('MS', 'Northwest Mississippi Association of Realtors', 'NWMSAR');
INSERT INTO temp_lookup_mls VALUES ('MS', 'Pearl River County Board of Realtors', 'PRCMLS');
INSERT INTO temp_lookup_mls VALUES ('MS', 'Southwest Mississippi Board of Realtors', 'SWMBOR');
INSERT INTO temp_lookup_mls VALUES ('MS', 'Vicksburg-Warren County Board of Realtors', 'VWCBR');
INSERT INTO temp_lookup_mls VALUES ('MO', 'Bagnell Dam Association of Realtors', 'BDAOR');
INSERT INTO temp_lookup_mls VALUES ('MO', 'Columbia Board of REALTORS®', 'CBORMLS');
INSERT INTO temp_lookup_mls VALUES ('MO', 'Cape Girardeau County Board of Realtors', 'CGCBR');
INSERT INTO temp_lookup_mls VALUES ('MO', 'Central Missouri Board of REALTORS', 'CMBOR');
INSERT INTO temp_lookup_mls VALUES ('MO', 'Southern Missouri Regional MLS, LLC (SOMO)', 'GSBOR');
INSERT INTO temp_lookup_mls VALUES ('MO', 'Heartland Multiple Listing Service', 'HMLS');
INSERT INTO temp_lookup_mls VALUES ('MO', 'Jefferson City Area Board of Realtors MLS', 'JCABR');
INSERT INTO temp_lookup_mls VALUES ('MO', 'Lake of the Ozarks Board of Realtors', 'LOOBOR');
INSERT INTO temp_lookup_mls VALUES ('MO', 'Mineral Area Board of Realtors', 'MABOR');
INSERT INTO temp_lookup_mls VALUES ('MO', 'Mid America Regional Information Systems, Inc.', 'MARIS');
INSERT INTO temp_lookup_mls VALUES ('MO', 'Northeast Central Board of Realtors - MO', 'NCBR');
INSERT INTO temp_lookup_mls VALUES ('MO', 'Ozark Gateway Association of Realtors', 'OGAR');
INSERT INTO temp_lookup_mls VALUES ('MO', 'Randolph County Board of Realtors', 'RCBR');
INSERT INTO temp_lookup_mls VALUES ('MO', 'South Central Board of Realtors-MO', 'SCBR');
INSERT INTO temp_lookup_mls VALUES ('MO', 'West Central Association of REALTORS®', 'SEDWAR');
INSERT INTO temp_lookup_mls VALUES ('MO', 'St. Joseph Regional Association of REALTORS®', 'SJRAR');
INSERT INTO temp_lookup_mls VALUES ('MO', 'Three Rivers Board of Realtors', 'TRBR');


CREATE TABLE IF NOT EXISTS lookup_mls (
  id serial,
  state varchar NOT NULL,
  full_name varchar NOT NULL,
	mls varchar,
  rm_inserted_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now_utc(),
  rm_modified_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now_utc(),
  CONSTRAINT lookup_mls_state_id_fk FOREIGN KEY (state)
    REFERENCES lookup_us_states (code) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT lookup_mls_mult_unique UNIQUE (state, full_name, mls),
  PRIMARY KEY (id) NOT DEFERRABLE INITIALLY IMMEDIATE
)
WITH (OIDS=FALSE);

DROP TRIGGER IF EXISTS update_modified_time_lookup_mls ON lookup_mls;

CREATE TRIGGER update_modified_time_lookup_mls
BEFORE UPDATE ON lookup_mls
FOR EACH ROW EXECUTE PROCEDURE update_rm_modified_time_column();

INSERT INTO lookup_mls (state, full_name, mls)
   SELECT state_name, full_name, mls
   FROM temp_lookup_mls
 ON CONFLICT (state, full_name, mls)
 DO UPDATE SET
  state = EXCLUDED.state,
  full_name = EXCLUDED.full_name,
  mls = EXCLUDED.mls;

COMMIT;

DROP TABLE temp_lookup_mls;
