#!/bin/bash

# example use ./scripts/misc/allHerokuApps config:set KEY=VALUE
set -e
set -o pipefail
DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null && pwd )"
cd "$DIR/.."


for app in `heroku apps | tail -n +2`
do
    # there may be no equivalent command using hk, so we have to use the bare heroku command
    heroku "$@" --app=$app
done
