#!/usr/bin/env node

/*
Simple script to utilize our aws service

options:
--action: function to call on service.aws
--fileName: full path of whatever file
--bucket: bucket name in config_external_accounts
*/

var coffee = require('coffee-script')
coffee.register()

var aws = require('../../backend/services/service.aws'),
  argv = require('yargs').argv,
  fs = require('fs'),
  path = require('path')


handle = aws[argv.action] || aws.postObject

if (!argv.bucket) {
  console.error('--bucket required')
  process.exit(122)
}

if (!argv.fileName) {
  console.error('--fileName required to postObject!')
  process.exit(123)
}

function getUserHome() {
  return process.env.HOME || process.env.USERPROFILE;
}

var fileName = argv.fileName

if (fileName.indexOf('~') > -1) {
  fileName = argv.fileName.replace('~', getUserHome())
}
console.log("attempting to load file: " + fileName)

var uploadFileName = path.parse(argv.fileName).base

handle({
  bucket: argv.bucket,
  key: uploadFileName,
  body: fs.createReadStream(fileName)
})
.then(function() {
  console.log(argv.action + ' success!!' + ' for filenamed ' + uploadFileName)
  process.exit(0)
})
.catch(function(error) {
  console.error(error)
  process.exit(200)
})
