#!/bin/bash
set -e
set -o pipefail

for ((i=1; i<=$#; i++))
do
    case "${!i}" in
        --debug)
            export IS_DEBUG=true
            ;;
        --debug=*)
            export IS_DEBUG=true
            export USE_DEBUG_PORT="${!i:8}"
            ;;
    esac
done

if [[ "$IS_DEBUG" == "true" ]]; then
  mocha --debug-brk --compilers coffee:coffee-script/register $@
else
  mocha --reporter spec --compilers coffee:coffee-script/register --timeout 10000 $@
fi
