#!/bin/bash

if ! hash coffee &> /dev/null || [[ $IS_HEROKU = 1 ]];then
  npm install -g coffee-script
fi
#TODO add findProcs to add matches and ignores
kill -9 $(ps aux | grep node | grep coffee | grep -v grep | grep -v Atom | grep -v findProcs | awk '{print $2}')

if ! hash gulp &> /dev/null || [[ $IS_HEROKU = 1 ]];then
  #gulp 4 branch sha#
  npm install -g gulp@'git+https://github.com/gulpjs/gulp.git#c120a948a1273581a9c1503bf6d80fe628710c64'
fi

#https://github.com/karma-runner/karma-coverage/issues/59 (why karma-cli only)
if ! hash karma-cli &> /dev/null || [[ $IS_HEROKU = 1 ]];then
  npm install -g karma-cli
fi

if ! hash node-debug &> /dev/null || [[ $IS_HEROKU = 1 ]];then
  npm install -g node-debug
fi
