#!/bin/bash

# first, make sure you have latest npm
npm install -g npm@2.x

#TODO figure out why this is rejecting git projects
#if ! hash npm-shrinkwrap &> /dev/null || [[ $IS_HEROKU = 1 ]];then
#  npm install -g npm-shrinkwrap
#fi

if ! hash coffee &> /dev/null || [[ $IS_HEROKU = 1 ]];then
  npm install -g coffee-script
fi
#TODO add findProcs to add matches and ignores
kill -9 $(ps aux | grep node | grep coffee | grep -v grep | grep -v Atom | grep -v findProcs | awk '{print $2}')

if ! hash gulp &> /dev/null || [[ $IS_HEROKU = 1 ]];then
  #gulp 4 branch sha#
  npm install -g gulp@'git+https://github.com/gulpjs/gulp.git#7243d6ead83c2e18236b9323be4a9265dcd511b6'
fi

#https://github.com/karma-runner/karma-coverage/issues/59 (why karma-cli only)
if ! hash karma-cli &> /dev/null || [[ $IS_HEROKU = 1 ]];then
  npm install -g karma-cli
fi

if ! hash bower &> /dev/null || [[ $IS_HEROKU = 1 ]];then
  npm install -g bower
fi

if ! hash node-debug &> /dev/null || [[ $IS_HEROKU = 1 ]];then
  npm install -g node-debug
fi
