#!/bin/bash

# first, make sure you have latest npm
# first, make sure you have latest npm

# if you want pure latest npm then `npm show npm version`
LATEST_NPM=`npm show npm@2.X version | tail -n 1 | awk '{print $2}'`
LATEST_NPM=$(echo $LATEST_NPM | sed "s/\'//g")
CURRENT_NPM=`npm --version`

echo "latest npm: $LATEST_NPM"
echo "current npm: $CURRENT_NPM"
if [[ $LATEST_NPM != $CURRENT_NPM ]];then
  npm install -g npm@2.x
fi

exit 0

#TODO figure out why this is rejecting git projects
#if ! hash npm-shrinkwrap &> /dev/null || [[ $IS_HEROKU = 1 ]];then
#  npm install -g npm-shrinkwrap
#fi

if ! hash coffee &> /dev/null || [[ $IS_HEROKU = 1 ]];then
  npm install -g coffee-script
fi
#TODO add findProcs to add matches and ignores
kill -9 $(ps aux | grep node | grep coffee | grep -v grep | grep -v Atom | grep -v findProcs | awk '{print $2}')

if ! hash gulp &> /dev/null || [[ $IS_HEROKU = 1 ]];then
  #gulp 4 branch sha#
  npm install -g gulp@'git+https://github.com/gulpjs/gulp.git#c120a948a1273581a9c1503bf6d80fe628710c64'
fi

#https://github.com/karma-runner/karma-coverage/issues/59 (why karma-cli only)
if ! hash karma-cli &> /dev/null || [[ $IS_HEROKU = 1 ]];then
  npm install -g karma-cli
fi

if ! hash node-debug &> /dev/null || [[ $IS_HEROKU = 1 ]];then
  npm install -g node-debug
fi
