#!/bin/bash

###
# See README.md for examples of how to use this script
###

set -e
set -o pipefail
SCRIPT_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null && pwd )/.."
cd "$SCRIPT_DIR/.."


ACTION_TYPE="$1"
shift

ACTION_TARGET="$1"
shift

if [[ "$@" != "" ]]
then
    DB_TARGETS=""
    for target in $@
    do
        if [[ "$target" == "prod" || "$target" == "production" ]]
        then
            DB_TARGETS="$DB_TARGETS realtymaps-map"
        elif [[ "$target" == *realtymaps-map ]]
        then
            DB_TARGETS="$DB_TARGETS $target"
        elif [[ "$target" == "local" || "$target" == "localhost" ]]
        then
            DB_TARGETS="$DB_TARGETS localhost"
        else
            DB_TARGETS="$DB_TARGETS ${target}-realtymaps-map"
        fi
    done
else
    DB_TARGETS=`heroku apps | tail -n +2 | cut -f1 -d' '`
fi


export LOG_LEVEL='warn'
SQL_COMMAND=`foreman run coffee --eval "require('./backend/services/service.externalAccounts').${ACTION_TYPE}AccountInfo('''${ACTION_TARGET}''', {logOnly: true}).then (result) -> process.exit(0)"`

if [[ "${ACTION_TYPE}" == "get" ]]
then
    echo "$SQL_COMMAND"
    exit 0
fi


# handle bad knex escaping
SQL_COMMAND=${SQL_COMMAND//\\"/"}
echo "SQL command: $SQL_COMMAND"


for app in $DB_TARGETS
do
    echo
    echo "Executing on MAIN_DATABASE@${app}..."
    if [[ "${app}" == "localhost" ]]
    then
        DB_TARGET=''
    else
        DB_TARGET="@${app}"
    fi
    psql -d `foreman run ./scripts/database/getDbUrl MAIN_DATABASE${DB_TARGET}` --command="${SQL_COMMAND}"
done
echo
