#!/bin/bash

export WEB_CONCURRENCY=1
export USER_DATABASE_URL=postgres://dev:devpass@localhost:5432/realtymaps_users_dev
export PROPERTY_DATABASE_URL=postgres://dev:devpass@localhost:5432/realtymaps_property_dev
export TEST_DATABASE_URL=postgres://dev:devpass@localhost:5432/realtymaps_test_dev
export NODE_ENV=development
export LOB_TEST_API_KEY=test_8374430ae1d67c906f09a27193f492f81ee
export LOB_LIVE_API_KEY=test_8374430ae1d67c906f09a27193f492f81ee
export APP_BASENAME=map
export HIREFIRE_TOKEN=dummy

#dev@realtymaps.com public key
export MAPBOX_API_KEY=pk.eyJ1IjoicmVhbHR5bWFwcyIsImEiOiJ4ZmtCNTVVIn0.eQ5DLSACcb7Y9xgQTBQ57A
export MAPBOX_API_UPLOAD_KEY=sk.eyJ1IjoicmVhbHR5bWFwcyIsImEiOiJJSDNYdmxjIn0.yO-KypiKbAsE90P2oYKGgQ
export MAPBOX_ACCOUNT=realtymaps
export MAPBOX_MAPS_MAIN=realtymaps.f33ce76e

export CARTODB_API_KEY=c95946d99453dfe16168c2d482f949a3d813f583
export CARTODB_MAPS='[{"name": "parcels", "mapId":"realtymaps@cf4dfc82@da8e5116f5a707eb037b32badce99811:1432133845689.5198"},{"name": "parcelsAddresses", "mapId":"realtymaps@2b9a4482@63498147d11dcb408f3e6b24e34dedcc:1432133845689.5198"}]'
export CARTODB_ACCOUNT=realtymaps
export CARTODB_API_KEY_TO_US=98d64004-be29-4f51-b883-1da478cf8f3d


npm start
