#!/bin/bash
set -e
set -o pipefail

CURRENT_DIR=$(dirname "${BASH_SOURCE[0]}")

"$CURRENT_DIR"/installPackageManager


if [[ "$IS_HEROKU" != "" || "$CI" != "" ]]; then
  # this is for local dev install needs ONLY!
  # for Heroku use buildpacks for this sort of thing
  # for CircleCI use circle.yml for this sort of thing
  exit 0
fi

platform='unknown'
unamestr=`uname`

if [[ "$unamestr" == 'Linux' ]]; then
  #http://sharp.dimens.io/en/stable/install/
  curl -s https://raw.githubusercontent.com/lovell/sharp/master/preinstall.sh | sudo bash -
  sudo apt-get install -y libpoppler-cpp-dev

elif [[ "$unamestr" == 'Darwin' ]]; then
  #http://sharp.dimens.io/en/stable/install/
  # NOTE these libraries are a pain in the ass with brew, as upgrade will blindly update vips and poppler c libs
  # the node libs dependend on specific versions
  # TO drop to an old version do
  # brew uninstall poppler --ignore-dependencies
  # brew uninstall vips
  # rm all versions of vips except one of the old ones you want
  # then `brew link vips poppler`
  if ! hash vips &> /dev/null || [[ $IS_HEROKU = 1 ]];then
    brew install homebrew/science/vips --with-imagemagick --with-webp
  fi
  if ! hash /usr/local/Cellar/poppler &> /dev/null || [[ $IS_HEROKU = 1 ]];then
    brew install poppler
  fi
fi

exit 0
