#!/bin/bash
set -e
set -o pipefail


# first, make sure you have latest npm

# if you want pure latest npm then `npm show npm version`
LATEST_NPM=`npm show npm@2.X version | tail -n 1 | awk '{print $2}'`
LATEST_NPM=$(echo $LATEST_NPM | sed "s/\'//g")
CURRENT_NPM=`npm --version`

echo "latest npm: $LATEST_NPM"
echo "current npm: $CURRENT_NPM"
if [[ $LATEST_NPM != $CURRENT_NPM ]];then
  npm install -g npm@2.x
fi


if [[ "$IS_HEROKU" != "" || "$CI" != "" ]]; then
  # this is for local dev install needs ONLY!
  # for Heroku use buildpacks for this sort of thing
  # for CircleCI use circle.yml for this sort of thing
  exit 0
fi

platform='unknown'
unamestr=`uname`

if [[ "$unamestr" == 'Linux' ]]; then
  #http://sharp.dimens.io/en/stable/install/
  curl -s https://raw.githubusercontent.com/lovell/sharp/master/preinstall.sh | sudo bash -
  sudo apt-get install -y libpoppler-cpp-dev

elif [[ "$unamestr" == 'Darwin' ]]; then
  #http://sharp.dimens.io/en/stable/install/
  if ! hash vips &> /dev/null || [[ $IS_HEROKU = 1 ]];then
    brew install homebrew/science/vips --with-imagemagick --with-webp
  fi
  if ! hash /usr/local/Cellar/poppler &> /dev/null || [[ $IS_HEROKU = 1 ]];then
    brew install poppler
  fi
fi

exit 0
