#!/bin/bash
set -e
set -o pipefail


if [[ "$IS_HEROKU" != "" || "$CI" != "" ]]; then
  # use buildpacks if HEROKU
  # use circle.ym if CI
  exit 0
fi

platform='unknown'
unamestr=`uname`

if [[ "$unamestr" == 'Linux' ]]; then
  #http://sharp.dimens.io/en/stable/install/
  curl -s https://raw.githubusercontent.com/lovell/sharp/master/preinstall.sh | sudo bash -
  sudo apt-get install -y libpoppler-cpp-dev

elif [[ "$unamestr" == 'Darwin' ]]; then
  #http://sharp.dimens.io/en/stable/install/
  if ! hash vips &> /dev/null || [[ $IS_HEROKU = 1 ]];then
    brew install homebrew/science/vips --with-imagemagick --with-webp
  fi
  if ! hash /usr/local/Cellar/poppler &> /dev/null || [[ $IS_HEROKU = 1 ]];then
    brew install poppler
  fi
fi

exit 0
