#!/bin/bash
set -e

SCRIPT_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null && pwd )/.."


if [ "$#" -lt 2 ]
then
    echo "usage: `basename $0` <heroku|github> <project> [--dbsync]"
    exit 1
fi


if [[ "$CIRCLECI" == "" ]]
then
    # manually run
    echo "ERROR: This is only intended to be run by CircleCI."
    exit 1
fi


SERVICE="$1"
PROJECT="$2"
if [[ "$CIRCLE_BRANCH" != "master" ]]
then
    PREFIX=`echo "$CIRCLE_BRANCH" | cut -d '/' -f 2`
    if [[ "$PREFIX" != "" ]]
    then
        PROJECT="$PREFIX-$PROJECT"
    fi
fi
DO_DBSYNC="$3"

echo "PUSH_TO: attempting to push to master on ${PROJECT} at ${SERVICE}"



if [[ "$CIRCLE_BRANCH" == "master" && "$CIRCLE_PROJECT_USERNAME" != "realtymaps" ]]
then
    # safety check -- we only want to push from master if we're on the main
    # "realtymaps" fork, so we're going to bail out here
    echo "PUSH_TO: refusing to push changes from master on ${CIRCLE_PROJECT_USERNAME}"
    exit 0
fi



# do the push
echo "PUSH_TO: pushing to ${SERVICE}"
if [[ "${SERVICE}" == "heroku" ]]
then
    echo "PUSH_TO: unshallowing git clone"
    git fetch --all --unshallow
    echo "PUSH_TO: doing push"
fi
git push --force "git@${SERVICE}.com:${PROJECT}.git" "${CIRCLE_SHA1}:master"

