#!/bin/bash
set -e
set -o pipefail


if [[ "$@" == "" ]]
then
    echo "Must supply dependency list to update"
    exit 1
fi

OPTIONS=()
DEPS=()

for ((i=1; i<=$#; i++))
do
    item="${!i}"
    if [[  "$item" =~ \-\- ]]; then
      OPTIONS+=("$item")
    else
      DEPS+=("$item")
    fi
done

# echo OPTIONS "$OPTIONS"

# make sure nothing extraneous exists
#???? see https://github.com/yarnpkg/yarn/issues/696
yarn install

# remove the indicated deps
for i in "${DEPS[@]}"
do
  # echo Removing $i
	rm -rf "./node_modules/$i"
done

# remove the shrinkwrap file
rm -f yarn.lock

# install new versions of removed deps
yarn add "$OPTIONS"
