#!/bin/bash


# the 'heroku' command doesn't get installed on heroku instances, so to be consistent we'll just use 'hk' everywhere

HK_APP="$1"
HK_COMMAND="$2"
shift
shift


# choose location for hk
if [[ "$IS_HEROKU" == "1" ]]
then
    HK_LOCATION=/app/hk
elif [[ "$CIRCLECI" != "" ]]
then
    HK_LOCATION=~/bin/hk
else
    HK_LOCATION=/tmp/hk
fi


# install it if needed, but be quiet about it
if [ ! -f "$HK_LOCATION" ]
then
    echo -n "Installing hk... " >&2
    curl -sL -A "`uname -sp`" https://hk.heroku.com/hk.gz | zcat >$HK_LOCATION && chmod +x $HK_LOCATION || (echo "" && exit 1)
    echo "done." >&2
fi


if [[ "$HK_APP" == "-" ]]
then
    # don't specify an app
    HK_APP=""
else
    HK_APP="-a $HK_APP"
fi


# run the command
$HK_LOCATION $HK_COMMAND $HK_APP "$@"
