#!/bin/bash
set -e

destTable=$1
frmTable=$2
fipsCode=$3
shift

sql="""UPDATE $destTable
set street_address_num=subq.street_address_num,
the_geom=subq.the_geom,
is_active=1,
num_updates=$destTable.num_updates + 1
FROM
(SELECT * FROM $frmTable) subq
where $destTable.rm_property_id = subq.rm_property_id;

INSERT INTO $destTable
SELECT id, name, (not is_active::boolean)::int, 1, code
FROM $frmTable
WHERE NOT EXISTS (
		SELECT * FROM $destTable
		WHERE
		id = $frmTable.id
	);

DELETE FROM $destTable
where id in (
select $destTable.id
from $destTable
LEFT JOIN $frmTable on $destTable.id = $frmTable.id
where $frmTable.id isnull and $destTable.code = '$fipsCode'
);"""
