#!/bin/sh
list=${1:-'./serverlist'}
for server in $(cat "$list")
do
  ping -oc 1 $server > /dev/null 2>&1
  if [ $? -eq 0 ] ; then
    echo "$server = running"
  else
    echo "$server = not running"
  fi
done
