#!/bin/sh
set -e

DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null && pwd )"
cd "$DIR/.."


./flyway/doFlyway.sh userManagement "$USER_DATABASE_URL" migrate
./flyway/doFlyway.sh propertyData "$PROPERTY_DATABASE_URL" migrate
