#!/bin/sh
set -e

if [ ! -n "$IS_HEROKU" ]
then
    DIR="$( cd -P "$( dirname "$0" )" > /dev/null && pwd )"
    cd "$DIR/.."
fi

# needed if we need to update the jars, they are in github soe no need to bundle
# ./bower_components/dbsync/bundle
./bower_components/dbsync/doFlyway.sh userManagement "$USER_DATABASE_URL" false migrate
./bower_components/dbsync/doFlyway.sh propertyData "$PROPERTY_DATABASE_URL" false migrate
