#!/bin/bash
if ! hash bowerfresh &> /dev/null || [[ $IS_HEROKU = 1 ]];then
  npm install -g bowerfresh@0.0.1
fi

#TODO figure out why this is rejecting git projects
#if ! hash npm-shrinkwrap &> /dev/null || [[ $IS_HEROKU = 1 ]];then
#  npm install -g npm-shrinkwrap
#fi

if ! hash coffee &> /dev/null || [[ $IS_HEROKU = 1 ]];then
  npm install -g coffee-script
fi
#TODO add findProcs to add matches and ignores
kill -9 $(ps aux | grep node | grep coffee | grep -v grep | grep -v Atom | grep -v findProcs | awk '{print $2}')

if ! hash gulp &> /dev/null || [[ $IS_HEROKU = 1 ]];then
  npm install -g gulp
fi

if ! hash karma &> /dev/null || [[ $IS_HEROKU = 1 ]];then
  npm install -g karma
fi

