#!/bin/bash
set -e

export GULP_COLOR="--color"

for ((i=1; i<=$#; i++))
do
    case "${!i}" in
        --clean)
            DO_CLEAN=true
            DO_INSTALL=true
            ;;
        --install)
            DO_INSTALL=true
            ;;
        --skip-dbsync)
            export SKIP_DBSYNC=true
            ;;
        --bare-server)
            export BARE_EXPRESS_SERVER=true
            ;;
        --mayday)
            export MAYDAY_OPTS="-e .env-mayday"
            ;;
        --skip-nginx)
            export SKIP_NGINX=true
            ;;
        --no-gulp-colors)
            export GULP_COLOR="--no-color"
            ;;
    esac
done


if [[ "$DO_CLEAN" == "true" ]]
then
  foreman run $MAYDAY_OPTS npm run clean
fi

if [[ "$DO_INSTALL" == "true" ]]
then
  foreman run $MAYDAY_OPTS npm install
fi

foreman run $MAYDAY_OPTS npm start
