#!/bin/bash
set -e
set -o pipefail

export GULP_COLOR="--color"

for ((i=1; i<=$#; i++))
do
    case "${!i}" in
        --really-clean)
            export DO_CACHE_CLEAN=true
            DO_CLEAN=true
            DO_INSTALL=true
            ;;
        --clean)
            DO_CLEAN=true
            DO_INSTALL=true
            ;;
        --install)
            DO_INSTALL=true
            ;;
        --skip-dbsync)
            export SKIP_DBSYNC=true
            ;;
        --gulp-*)
            export GULP_TARGET="${!i:7}"
            ;;
        --skip-nginx)
            export SKIP_NGINX=true
            ;;
        --no-gulp-colors)
            export GULP_COLOR="--no-color"
            ;;
        --debug)
            export IS_DEBUG=true
            ;;
        --debug=*)
            export IS_DEBUG=true
            export USE_DEBUG_PORT="${!i:8}"
            ;;
        --logs=*)
            export LOG_ENABLE="${!i:7}"
            ;;
        *)
            echo "runDev: unexpected command line option: ${!i}"
            exit 0
            ;;
    esac
done


if [[ "$DO_CLEAN" == "true" ]]
then
  foreman run npm run clean
fi

if [[ "$DO_INSTALL" == "true" ]]
then
  foreman run npm install
fi

foreman run npm start
