#!/bin/bash
set -e

if [[ "$1" == "--clean" || "$2" == "--clean" ]]
then
  INSTALL=1
  foreman run npm run clean
fi

if [[ "$1" == "--install" || "$2" == "--install" || "$INSTALL" == "1" ]]
then
  foreman run npm install
fi

foreman start -c web=1,dbsync=0
