#!/bin/bash
set -e

if [ ! -n "$IS_HEROKU" ]
then
    DIR="$( cd -P "$( dirname "$0" )" > /dev/null && pwd )"
    cd "$DIR/.."
fi


if [[ $PORT -eq 5000 ]];then
  unset PORT
fi

if [ -n "$IS_HEROKU" ]; then
  gulp prod
else
  gulp
fi
