#!/bin/sh
set -e


echo "====================="
pwd
echo "====================="

DIR="$( cd -P "$( dirname "$0" )" > /dev/null && pwd )"
cd "$DIR/.."

if [ -n "$IS_HEROKU" ] ; then
  echo "in Heroku, exiting"
  exit 0
fi


#or 4000
argPorts=${1:-"3000,4000"}
ports=(${argPorts//,/ })

for i in "${!ports[@]}"
do
  PID=$(./scripts/getRunningPID)
  if [[ -n $PID ]]; then
    kill $PID
    someThingWasKilled='true'
  else
    if [[ -z $someThingWasKilled ]];then
      echo "We're good, nothing running to stop."
    fi
  fi
done
