#!/bin/bash
set -e
set -o pipefail
DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null && pwd )"
cd "$DIR/.."
# set -x

###########################
####### set up dump #######
###########################

# use "custom" pg_dump/pg_restore format, probably the most efficient and flexible
DUMP_COMMAND="pg_dump -F c"

# only dump from the public schema
DUMP_COMMAND="$DUMP_COMMAND -n public"

# skip the table created by the postgis extension, it's already in place
DUMP_COMMAND="$DUMP_COMMAND -T spatial_ref_sys"

# dump from the source db
SRC_URL=`./database/getDbUrl $1`
SRC_DB=`./database/getDbName $1`
DUMP_COMMAND="$DUMP_COMMAND -d $SRC_URL"
shift


##############################
####### set up restore #######
##############################

# use "custom" pg_dump/pg_restore format, probably the most efficient and flexible
RESTORE_COMMAND="pg_restore -F c"

# restore to the destination db
DST_URL=`./database/getDbUrl $1`
DST_DB=`./database/getDbName $1`
RESTORE_COMMAND="$RESTORE_COMMAND -d $DST_URL"
shift

# do not try to set the owner of created objects
RESTORE_COMMAND="$RESTORE_COMMAND -O"

# restore as a single transaction
RESTORE_COMMAND="$RESTORE_COMMAND -1"


###################################
####### set up some options #######
###################################
if [[ "$1" == "--oids" ]]
then
    # means we want to dump OIDs so we can recreate foreign keys
    # we don't do this by default because it hurts efficiency
    DUMP_COMMAND="$DUMP_COMMAND -o"
    shift
fi

if [[ "$1" == "--table" && "$2" != "" ]]
then
  DUMP_COMMAND="$DUMP_COMMAND -t $2"
  shift
  shift
fi

if [[ "$1" == "--clean" ]]
then
    # drop existing objects before trying to create them
    RESTORE_COMMAND="$RESTORE_COMMAND -c"
    shift
fi
if [[ "$1" == "--manual" ]]
then
    # only echo the commands for manual execution
    MANUAL="true"
    shift
fi


################################
####### set what to dump #######
################################
if [[ "$@" != "" ]]
then
    # we have some restrictions on what to dump
    DUMP_COMMAND="$DUMP_COMMAND $@"
fi



if [[ "$MANUAL" == "true" ]]
then
    # echo and quit
    echo "CLONE: dump: $DUMP_COMMAND > /var/tmp/rm_dump.db"
    echo "CLONE: restore: $RESTORE_COMMAND < /var/tmp/rm_dump.db"
    exit 0
fi


######################
####### DO IT! #######
######################

START_TIME=`date '+%s'`
echo "CLONE: cloning from $SRC_DB to $DST_DB"

echo "CLONE: doing dump: $DUMP_COMMAND > /var/tmp/rm_dump.db"
$DUMP_COMMAND > /var/tmp/rm_dump.db
MID_TIME=`date '+%s'`
echo "CLONE: doing restore: $RESTORE_COMMAND < /var/tmp/rm_dump.db"
$RESTORE_COMMAND < /var/tmp/rm_dump.db
END_TIME=`date '+%s'`
echo "CLONE: time taken for dump: $(( MID_TIME - START_TIME ))s"
echo "CLONE: time taken for restore: $(( END_TIME - MID_TIME ))s"
