#!/bin/bash
set -e
if [[ $1 == '' ]]; then
  echo 'db name required'
  exit 201
fi

#https://realtymaps.atlassian.net/wiki/display/NDS/Database+Setup
SQL_STR="CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS postgis_topology;
CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;
CREATE EXTENSION IF NOT EXISTS postgis_tiger_geocoder;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS tablefunc;"

psql -d "realtymaps_$1" -U superdev -c "$SQL_STR"
