#!/bin/bash
set -e
if [[ $1 == '' ]]; then
  echo 'db name required'
  exit 201
fi

#https://realtymaps.atlassian.net/wiki/display/NDS/Database+Setup
psql -d "realtymaps_$1" -U superdev -c "CREATE EXTENSION IF NOT EXISTS postgis;"
psql -d "realtymaps_$1" -U superdev -c "CREATE EXTENSION IF NOT EXISTS postgis_topology;"
psql -d "realtymaps_$1" -U superdev -c "CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;"
psql -d "realtymaps_$1" -U superdev -c "CREATE EXTENSION IF NOT EXISTS postgis_tiger_geocoder;"
psql -d "realtymaps_$1" -U superdev -c "CREATE EXTENSION IF NOT EXISTS pg_trgm;"
psql -d "realtymaps_$1" -U superdev -c "CREATE EXTENSION IF NOT EXISTS tablefunc;"
