#!/bin/bash
set -e

SCRIPT_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null && pwd )/.."


if [[ "$SKIP_DBSYNC" == "true" ]]
then
    exit 0
fi


if [[ "$1" == "--to" ]]
then
    # means we have a specified db, don't use the configured one 
    DST_URL=`$SCRIPT_DIR/database/getDbUrl $2`?ssl=true
    DST_DB=`$SCRIPT_DIR/database/getDbName $2`
    shift
    shift
else
    DST_URL="$DATABASE_URL"
    DST_DB="main db"
fi

source $SCRIPT_DIR/environmentNormalization/dbsync


echo "SYNC: performing property db migrations on db: $DST_DB"
$DBSYNC --path migrations/propertyData --client pg --connection $DST_URL --reminder 1 --recursive
