#!/bin/bash
set -e
set -o pipefail

SCRIPT_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null && pwd )/.."

${SCRIPT_DIR}/database/clone MAIN_DATABASE@realtymaps-map MAIN_DATABASE --clean -t config_external_accounts
