#!/bin/bash
set -e
set -x

SCRIPT_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null && pwd )/.."


if [[ "$SKIP_DBSYNC" == "true" ]]
then
    exit 0
fi

DB_LABEL=`echo "$1" | tr '[a-z]' '[A-Z]'`
DST_URL=`$SCRIPT_DIR/database/getDbUrl ${DB_LABEL}_DATABASE`
DBSYNC_RESULT=/tmp/dbsync.result
S3_BUCKET=rmaps-dropbox

if [[ $1 == *"@"* ]]
then
    DST_URL="${DST_URL}?ssl=true"
fi

source $SCRIPT_DIR/environmentNormalization/dbsync


echo "SYNC: performing db migrations on: ${DB_LABEL}_DATABASE"
$DBSYNC --path migrations/$1 --client pg --connection $DST_URL --reminder 1 --recursive | tee "$DBSYNC_RESULT"


if [[ "$NODE_ENV" == "production" ]]
then
    echo "Checking for successful migrations"
    set +e
    migrationsResult=`fgrep "SUCCESS: " "$DBSYNC_RESULT" | fgrep " migrations performed"`
    set -e
    if [[ "$CI_DB_SECRET_KEY" == "" ]]
    then
        echo "ERROR: CI_DB_SECRET_KEY missing"
    fi
    if [[ "$migrationsResult" != "" ]]
    then
        DB_URL=`$SCRIPT_DIR/database/getDbUrl ${DB_LABEL}_DATABASE@$HEROKU_APP_NAME`
        cd /tmp

        echo "Dumping ${DB_LABEL} schema"
        if [[ $DB_LABEL == "NORMALIZED" ]]
        then
          tableList="-T 'tax_*' -T 'deed_*' -T 'mortgage_*'"
        fi
        pg_dump -x -n public -s -F c $tableList -d "$DB_URL" > "${CI_DB_SECRET_KEY}_${DB_LABEL}_SCHEMA"

        echo "Dumping ${DB_LABEL} dbsync_migrations"
        pg_dump -x -n public -a -F c -t dbsync_migrations -d "$DB_URL" > "${CI_DB_SECRET_KEY}_${DB_LABEL}_DBSYNC"

        echo "Uploading ${DB_LABEL} schema to S3"
        $SCRIPT_DIR/misc/bucket --bucket $S3_BUCKET --fileName "${CI_DB_SECRET_KEY}_${DB_LABEL}_SCHEMA"

        echo "Uploading ${DB_LABEL} dbsync_migrations to S3"
        $SCRIPT_DIR/misc/bucket --bucket $S3_BUCKET --fileName "${CI_DB_SECRET_KEY}_${DB_LABEL}_DBSYNC"

        cd -
    else
        echo "No schema changes"
    fi
else
    echo "Environment is $NODE_ENV, not dumping schema"
fi
