#!/bin/bash
set -e

SCRIPT_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null && pwd )/.."


if [[ "$SKIP_DBSYNC" == "true" ]]
then
    exit 0
fi


if [[ "$1" == "--to" ]]
then
    # means we have a specified db, don't use the configured one 
    DST_URL=`$SCRIPT_DIR/database/getDbUrl $2`?ssl=true
    DST_DB=`$SCRIPT_DIR/database/getDbName $2`
    shift
    shift
else
    DST_URL=`$SCRIPT_DIR/database/getDbUrl PROPERTY_DATABASE`
    DST_DB=PROPERTY_DATABASE
fi

source $SCRIPT_DIR/environmentNormalization/dbsync


echo "SYNC: performing property db migrations on db: $DST_DB"
$DBSYNC --path migrations/propertyData --client pg --connection $DST_URL --reminder 1 --recursive
echo "SYNC: staging dirty views"
$DBSYNC --path $SCRIPT_DIR/sql --client pg --connection $DST_URL --reminder 1 --blindly --forget --files 'stage_dirty_views.sql'
if [[ "$1" == "--breaking" ]]
then
    echo "SYNC: pushing all staged changes"
    $DBSYNC --path $SCRIPT_DIR/sql --client pg --connection $DST_URL --reminder 1 --blindly --forget --files 'push_all_staged_changes.sql'
else
    echo "SYNC: pushing non-breaking staged changes"
    $DBSYNC --path $SCRIPT_DIR/sql --client pg --connection $DST_URL --reminder 1 --blindly --forget --files 'push_nonbreaking_staged_changes.sql'
fi
