#!/bin/bash
set -e
set -o pipefail
DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null && pwd )"
cd "$DIR/.."


source $SCRIPT_DIR/environmentNormalization/dbsync

if [[ "$1" == "--fresh" ]]
then
    shift

    # note we connect to RAW_TEMP_DATABASE_URL below, but that's because you can't drop the database you're connected to,
    # and certainly not connect to it in order to create it, so RAW_TEMP_DATABASE_URL was a semi-arbitrary alternative
    echo
    echo "Removing old test db..."
    $DBSYNC --path $SCRIPT_DIR/sql --client pg --connection $RAW_TEMP_DATABASE_URL --reminder 1 --blindly --forget --autocommit --files 'drop_test_db.sql'
    echo
    echo "Creating fresh test db..."
    $DBSYNC --path $SCRIPT_DIR/sql --client pg --connection $RAW_TEMP_DATABASE_URL --reminder 1 --blindly --forget --autocommit --files 'create_test_db.sql'
    sleep 1
fi

echo
$DBSYNC --path ./migrations/test --client pg --connection "$TEST_DATABASE_URL" --reminder 1 "$@"
