#!/bin/sh
set -e
set -o pipefail


echo creating dev user:
# create the role used for migrations (use "devpass" as the password)
createuser -d -E -P dev

# create a superuser (use a secure password of your choice)
echo creating superdev user:
createuser -d -E -l -P -r -s superdev

# create our dbs (use "devpass" as the password each time prompted)
./scripts/database/createDbs dev

./scripts/database/createExtensions main superdev
./scripts/database/createExtensions normalized superdev

psql -d postgres://superdev@localhost:5432/realtymaps_main -f /tmp/main_dump.db
cp /tmp/pg_hba.conf ~/Library/Application\ Support/Postgres/var-9.6/pg_hba.conf
