columns = {}

module.exports =
  NUM_ROWS_TO_PAGINATE: 500
  BLACKKNIGHT_PROCESS_DATES: 'blackknight process dates'
  TAX: 'ASMT'
  DEED: 'Deed'
  MORTGAGE: 'SAM'
  REFRESH: 'Refresh'
  UPDATE: 'Update'
  LAST_COMPLETE_CHECK: 'last complete check'
  DELETE: 'Delete'
  LOAD: 'Load'
  COLUMNS: columns


columns[module.exports.DELETE] = {}
columns[module.exports.DELETE][module.exports.REFRESH] = {}
columns[module.exports.DELETE][module.exports.REFRESH][module.exports.TAX] = [
  "FIPS Code"
  "Edition"
  "Load Date"
]
columns[module.exports.DELETE][module.exports.REFRESH][module.exports.DEED] = [
  "FIPS Code"
]
columns[module.exports.DELETE][module.exports.REFRESH][module.exports.MORTGAGE] = [
  "FIPS Code"
]

columns[module.exports.DELETE][module.exports.UPDATE] = {}
columns[module.exports.DELETE][module.exports.UPDATE][module.exports.TAX] = [
  "FIPS Code"
  "APN"
  "Edition"
  "Load Date"
]
columns[module.exports.DELETE][module.exports.UPDATE][module.exports.DEED] = [
  "FIPS Code"
  "PID"
]
columns[module.exports.DELETE][module.exports.UPDATE][module.exports.MORTGAGE] = [
  "FIPS Code"
  "PID"
]


columns[module.exports.LOAD] = {}
columns[module.exports.LOAD][module.exports.REFRESH] = {}
# load columns are the same whether refresh or update
columns[module.exports.LOAD][module.exports.UPDATE] = columns[module.exports.LOAD][module.exports.REFRESH]

columns[module.exports.LOAD][module.exports.REFRESH][module.exports.TAX] = [
  "FIPS Code"
  "BKFS Internal PID"
  "Assessor’s Parcel Number"
  "Duplicate APN"
  "Property Address Source Flag"
  "Property Full Street Address"
  "Property City Name"
  "Property State"
  "Property Zip Code"
  "Property Zip + 4"
  "Property Unit Type"
  "Property Unit Number"
  "Property House Number"
  "Property Street Direction Left"
  "Property Street Name"
  "Property Street Suffix"
  "Property Street Direction Right"
  "Property Address: Carrier Route"
  "Property Address: Latitiude"
  "Property Address: Longitude"
  "Property Address: Census Tract"
  "Assessee/Owner Name"
  "2nd Assessee/Owner Name (or 'DBA')"
  "Assessee/Owner Vesting Code"
  "Tax Account Number"
  "Mail Care-Of Name"
  "Assessee Mail: Full Street Address"
  "Assessee Mail: City Name"
  "Assessee Mail: State Code"
  "Assessee Mail: Zip Code"
  "Assessee Mail: Zip + 4"
  "Assessee Mail: Unit Type"
  "Assessee Mail: Unit Number"
  "Owner-Occupied (Residential)"
  "Assessed Land Value"
  "Assessed Improvement Value"
  "Total Assessed Value"
  "Assessment Year"
  "California Homeowner's Exemption"
  "Tax Exemption Codes"
  "Tax Rate Code Area"
  "Recorder's Document Number from Assessment"
  "Recorder's Book Number from Assessment"
  "Recorder's Page Number from Assessment"
  "Recording Date from Assessment"
  "Document Type from Assessment"
  "Sales Price from Assessment"
  "Sales Price Code from Assessment"
  "Prior Sale Date"
  "Prior Sales Price"
  "Prior Sales Price Code"
  "Tax Source"
  "Tax Amount"
  "Tax Year"
  "Tax Delinquent Year"
  "Legal: Brief Description"
  "Legal: Brief Description - FULL"
  "Legal: Lot Code"
  "Legal: Lot Number"
  "Legal: Land Lot"
  "Legal: Block"
  "Legal: Section"
  "Legal: District"
  "Legal: Unit"
  "Legal: City, Township, Municipality"
  "Legal: Subdivision Name"
  "Legal: Phase Number"
  "Legal: Tract Number"
  "Legal: Section/Township/ Range/Meridian"
  "Legal: Assessor's Map Ref"
  "Standardized Land Use Code"
  "Zoning"
  "Lot Size or Area"
  "Lot Size/Area Unit"
  "Original Lot Size or Area"
  "Building Area"
  "Year Built"
  "# of Buildings"
  "# of Stories"
  "Total Number of Rooms"
  "Number of Units"
  "Number of Bedrooms"
  "Number of Baths"
  "Number of Partial Baths"
  "Parking Type"
  "Parking - # of Cars"
  "Pool"
  "'Market' Value: Land"
  "'Market' Value: Improvement"
  "Total 'Market' Value"
  "'Market' Value Year"
  "Building Class"
  "Style"
  "Type Construction"
  "Exterior Walls"
  "Foundation"
  "Roof Cover"
  "Heating"
  "Air Conditioning"
  "Elevator"
  "Fireplace"
  "Basement"
  "Current Owner Name"
  "Current Owner: Mail Street Address"
  "Current Owner: Mailing City"
  "Current Owner: Mailing State"
  "Current Owner: Mailing Zip"
  "Current Owner: Mailing Zip4"
  "Current Owner: Unit Type"
  "Current Owner: Unit Number"
  "Current Owner: Mail Care of Name"
  "Assessment Source File Date"
  "Latest Sale - Recording Date"
  "Latest Sale - Book Number"
  "Latest Sale - Page Number"
  "Latest Sale - Document Number"
  "Latest Sale - Document Type Code"
  "Latest Sale - Price"
  "Latest Sale - Price Code"
  "Prior Sale - Recording Date"
  "Prior Sale - Book Number"
  "Prior Sale - Page Number"
  "Prior Sale - Document Number"
  "Prior Sale - Document Type Code"
  "Prior Sale - Price"
  "Prior Sale - Price Code"
  "Latest Valid - Recording Date"
  "Latest Valid - Book Number"
  "Latest Valid - Page Number"
  "Latest Valid - Document Number"
  "Latest Valid - Document Type Code"
  "Latest Valid - Price"
  "Latest Valid - Price Code"
  "Prior Valid - Recording Date"
  "Prior Valid - Book Number"
  "Prior Valid - Page Number"
  "Prior Valid - Document Number"
  "Prior Valid - Document Type Code"
  "Prior Valid - Price"
  "Prior Valid - Price Code"
  "Assessee (Owner) Name Indicator"
  "2nd Assessee (Owner) Name Indicator"
  "Mail Care-Of Name Indicator"
  "Assessee (Owner) Name Type"
  "2nd Assessee (Owner) Name Type"
  "Alt/Old APN Indicator"
  "Certification Date"
  "Lot Size - Square Feet"
  "Building Quality"
  "FLOOR COVER"
  "# of Plumbing Fixtures"
  "Building Area 1"
  "Building Area 1 Indicator"
  "Building Area 2"
  "Building Area 2 Indicator"
  "Building Area 3"
  "Building Area 3 Indicator"
  "Building Area 4"
  "Building Area 4 Indicator"
  "Building Area 5"
  "Building Area 5 Indicator"
  "Building Area 6"
  "Building Area 6 Indicator"
  "Building Area 7"
  "Building Area 7 Indicator"
  "Effective Year Built"
  "Heating Fuel Type"
  "Air Conditioning Type"
  "Lot Size - Acres"
  "Mortgage Lender Name"
  "Interior Walls"
  "School/Tax District 1"
  "School/Tax District 1 Indicator"
  "School/Tax District 2"
  "School/Tax District 2 Indicator"
  "School/Tax District 3"
  "School/Tax District 3 Indicator"
  "Site Influence"
  "Amenities"
  "Other Impr Building Indicator 1"
  "Other Impr Building Indicator 2"
  "Other Impr Building Indicator 3"
  "Other Impr Building Indicator 4"
  "Neighborhood Code"
  "Condo Project /  Bldg Name"
  "Other Impr Building Indicator 5"
  "Amenities 2"
  "Other Impr Building Area 1"
  "Other Impr Building Area 2"
  "Other Impr Building Area 3"
  "Other Impr Building Area 4"
  "Other Impr Building Area 5"
  "Other Rooms"
  "Extra Features 1 Area"
  "Extra Features 1 Indicator"
  "Topography"
  "Roof Type"
  "Extra Features 2 Area"
  "Extra Features 2 Indicator"
  "Extra Features 3 Area"
  "Extra Features 3 Indicator"
  "Extra Features 4 Area"
  "Extra Features 4 Indicator"
  "Old APN"
  "Building Condition"
  "Lot Size - Frontage Feet"
  "Lot Size - Depth Feet"
  "Comments: Summary of Building Cards"
  "Water"
  "Sewer"
  "Match Code"
  "Location Code"
  "RawPropertyHouseNumber"
  "RawPropertyHouseAlpha"
  "RawPropertyStreetDirectionLeft"
  "RawPropertyStreetName"
  "RawPropertyStreetSuffix"
  "RawPropertyStreetDirectionRight"
  "RawPropertyUnitNumber"
  "RawPropertyFullStreetAddress"
  "RawPropertyCityName"
  "RawPropertyState"
  "RawPropertyZipCode"
  "RawPropertyZip4"
  "RawMailingHouseNumber"
  "RawMailingHouseAlpha"
  "RawMailingStreetDirectionLeft"
  "RawMailingStreetName"
  "RawMailingStreetSuffix"
  "RawMailingStreetDirectionRight"
  "RawMailingUnitNumber"
  "RawMailingFullStreetAddress"
  "RawMailingCityName"
  "RawMailingState"
  "RawMailingZipCode"
  "RawMailingZip4"
  "Edition"
  "Owner1FirstName"
  "Owner1MiddleName"
  "Owner1LastName"
  "Owner2Firstname"
  "Owner2MiddleName"
  "Owner2LastName"
  "ParsedOwnerSourceCode"
]
columns[module.exports.LOAD][module.exports.REFRESH][module.exports.DEED] = [
  "FIPS Code"
  "Property Full Street Address"
  "Property City Name"
  "Property State"
  "Property Zip Code"
  "Property Zip + 4"
  "Property Unit Type"
  "Property Unit Number"
  "Property House Number"
  "Property Street Direction Left"
  "Property Street Name"
  "Property Street Suffix"
  "Property Street Direction Right"
  "Property Address: Carrier Route"
  "Recording Date"
  "Recorder’s Book Number"
  "Recorder’s Page Number"
  "Recorder’s Document Number"
  "Document Type Code"
  "Assessor’s Parcel NumberMulti-APN Flag"
  "Partial Interest Transferred"
  "#1 - Seller First Name & Middle Name"
  "#1 - Seller Last Name OR Corporation Name"
  "#1 - Seller ID Code"
  "#2 - Seller First Name & Middle Name"
  "#2 - Seller Last Name OR Corporation Name"
  "#2 - Seller ID Code"
  "#1 - Buyer First Name & Middle Name"
  "#1 - Buyer Last Name OR Corporation Name"
  "#1 - Buyer ID Code"
  "#2 - Buyer First Name & Middle Name"
  "#2 - Buyer Last Name OR Corporation Name"
  "Buyer Vesting Code"
  "Concurrent TD: Document Number or Book/Page"
  "Buyer Mail: City"
  "Buyer Mail: State"
  "Buyer Mail: Zip Code"
  "Buyer Mail: Zip + 4"
  "Legal: Lot Code"
  "Legal: Lot Number(s)"
  "Legal: Block"
  "Legal: Section"
  "Legal: District"
  "Legal: Land Lot"
  "Legal: Unit"
  "Legal: City, Township, Municipality"
  "Legal: Subdivision Name"
  "Legal: Phase Number"
  "Legal: Tract Number"
  "Legal: Brief Description"
  "Legal: Section/Township/ Range/Meridian"
  "Recorder's Map Reference"
  "Property/Buyer Mailing Address Code"
  "Property Use Code"
  "Original Date of Contract"
  "Sales Price"
  "Sales Price Code"
  "City Transfer Tax"
  "County Transfer Tax"
  "Total Transfer Tax"
  "Concurrent TD: Lender Name (Beneficiary)"
  "Concurrent TD: Lender Type"
  "Concurrent TD: Loan Amount"
  "Concurrent TD: Loan Type"
  "Concurrent TD: Type Financing"
  "Concurrent TD: Interest Rate"
  "Concurrent TD: Due Date"
  "Concurrent 2nd TD: Loan Amount"
  "Buyer Mail: Full Street Address"
  "Buyer Mail: Unit Type"
  "Buyer Mail: Unit Number"
  "BKFS Internal PID"
  "Buyer Mail: Care of Name"
  "Title Company Name"
  "Complete Legal Description Code"
  "Adjustable Rate Rider"
  "Adjustable Rate Index"
  "Change Index"
  "Rate Change Frequency"
  "Interest Rate Not Greater Than"
  "Interest Rate Not Less Than"
  "Maximum Interest Rate"
  "Interest Only Period"
  "Fixed/Step (Conversion) Rate Rider"
  "First Change Date - Year (Conversion Rider)"
  "First Change Date - Month & Day (Conversion Rider)"
  "Prepayment Rider"
  "Prepayment Term (Penalty Rider)"
  "Assessor's Land Use"
  "Residential Indicator"
  "Construction Loan"
  "Inter-Family"
  "Cash Purchase"
  "Stand-Alone Refi"
  "Equity Credit Line"
  "REO-Flag"
  "DistressedSaleFlag"
  "Seller Mail Address: Full Street"
  "Seller Mail Address: Unit Number"
  "Seller Mail Address: City Name"
  "Seller Mail Address: State Code"
  "Seller Mail Address: Zip Code"
  "Seller Mail Address: Zip + 4"
]
columns[module.exports.LOAD][module.exports.REFRESH][module.exports.MORTGAGE] = [
  "FIPS Code"
  "Property Full Street Address"
  "Property City Name"
  "Property State"
  "Property Zip Code"
  "Property Zip + 4"
  "Property Unit Type"
  "Property Unit Number"
  "Property House Number"
  "Property Street Direction Left"
  "Property Street Name"
  "Property Street Suffix"
  "Property Street Direction Right"
  "Property Address: Carrier Route"
  "Record Type"
  "Recording Date"
  "Recorder’s Book Number"
  "Recorder’s Page Number"
  "Recorder’s Document Number"
  "Assessor’s Parcel Number"
  "#1 - Borrower First Name & Middle Name"
  "#1 - Borrower Last Name OR Corporation Name"
  "#1 - Borrower ID Code"
  "#2 - Borrower First Name & Middle Name"
  "#2 - Borrower Last Name OR Corporation Name"
  "#2 - Borrower ID Code"
  "Borrower Vesting Code"
  "Legal: Lot Number(s)"
  "Legal: Block"
  "Legal: Section"
  "Legal: District"
  "Legal: Land Lot"
  "Legal: Unit"
  "Legal: City, Township, Municipality"
  "Legal: Subdivision Name"
  "Legal: Phase Number"
  "Legal: Tract Number"
  "Legal: Brief Description"
  "Legal: Section/Township/ Range/Meridian"
  "Lender Name (Beneficiary)"
  "Lender Name ID"
  "Lender Type"
  "Loan Amount"
  "Loan Type"
  "Type Financing"
  "Interest Rate"
  "Due Date"
  "Adjustable Rate Rider"
  "Adjustable Rate Index"
  "Change Index"
  "Rate Change Frequency"
  "Interest Rate Not Greater Than"
  "Interest Rate Not Less Than"
  "Maximum Interest Rate"
  "Interest Only Period"
  "Fixed/Step (Conversion) Rate Rider"
  "First Change Date - Year (Conversion Rider)"
  "First Change Date - Month & Day (Conversion Rider)"
  "Prepayment Rider"
  "Prepayment Term (Penalty Rider)"
  "Buyer Mail: Full Street Address"
  "Borrower Mail: Unit Number"
  "Borrower Mail: City"
  "Borrower Mail: State"
  "Borrower Mail: Zip Code"
  "Borrower Mail: Zip + 4"
  "Original Date of Contract"
  "Title Company Name"
  "Lender DBA Name"
  "Lender Mail: Full Street Address"
  "Lender Mail: Unit"
  "Lender Mail: City"
  "Lender Mail: State"
  "Lender Mail: Zip Code"
  "Lender Mail: Zip + 4"
  "Loan Term - Months"
  "Loan Term - Years"
  "Loan Number"
  "Current Sale - Document Number"
  "Current Sale - Book Number"
  "Current Sale - Page Number"
  "Current Sale - Recording Date"
  "Current Sale - Price"
  "Current Sale - Price Code"
  "LPS Internal PID"
  "Assessor's Land Use"
  "Residential Indicator"
  "Construction Loan"
  "Cash Purchase"
  "Stand-Alone Refi"
  "Equity Credit Line"
]
