# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"
Vagrant::configure(VAGRANTFILE_API_VERSION) do |config|
  # Project name
  project = 'rlm-realtymaps.vm'

  # Base box
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  # Network
  # If this throws an error when booting up the vm restart VirtualBox in OS X
  # https://github.com/mitchellh/vagrant/issues/1671#issuecomment-22146167
  # VirtalBox >= 4.2.0: sudo /Library/StartupItems/VirtualBox/VirtualBox restart
  #
  # For VirtualBox 4.3, if you uninstall using the tool and do a full reinstall
  # it will fix this issue. If you still need to restart, use the following command:
  # VirtualBox > 4.3.0: sudo launchctl load /Library/LaunchDaemons/org.virtualbox.startup.plist
  config.vm.hostname = project
  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network :private_network, ip: "10.11.12.13"
  config.ssh.forward_agent = true

  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.
  config.vm.provider :virtualbox do |vm|
    vm.customize ["modifyvm", :id, "--name", project]
    vm.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vm.customize ["modifyvm", :id, "--memory", 2048]
  end

  # Set the Timezone to something useful
  #config.vm.provision :shell, :inline => "echo \"America/New_York\" | sudo tee /etc/timezone && dpkg-reconfigure --frontend noninteractive tzdata"

  # Shared folder
  config.vm.synced_folder "../../", "/vagrant", owner: 'www-data', group: 'www-data', mount_options: ["dmode=777", "fmode=777"]

  #http://blog.doismellburning.co.uk/2013/01/19/upgrading-puppet-in-vagrant-boxes/
  ["puppet-ubuntu-bugs.sh", "update-puppet.sh"].each do |file_name|
    config.vm.provision :shell, :path => file_name
  end

  # Enable the Puppet provisioner
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path   = ".puppet/manifests"
    puppet.module_path      = ".puppet/modules"
    puppet.options          = ['--verbose', '--debug']
  end
end
