--
-- PostgreSQL database dump
--

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

SET search_path = public, pg_catalog;

--
-- Data for Name: data_source_fields; Type: TABLE DATA; Schema: public; Owner: dev
--

INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (1, 'Fips Code', 'FipsCode', 'Fips Code', 'Character', '', 'FIPS_CODE', 'Federal Information Processing Standards codes used nationally to numerically identify a specific county or political jurisdiction.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (2, 'Apn Unformatted', 'ApnUnformatted', 'Apn Unformatted', 'Character', '', 'APN_UNFORMATTED', 'Assessor''s Parcel Number in an unformatted form. This is most often used by the county and others as a unique key (e.g.,10132021A)', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (3, 'Apn Sequence Number', 'ApnSequenceNumber', 'Apn Sequence Number', 'Int', '', 'APN_SEQUENCE_NUMBER', 'This internal sequence number is used to ensure "unique-ness" of the Assessor''s Parcel Number (e.g., 10132021A seq 001)', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (4, 'Apn Formatted', 'ApnFormatted', 'Apn Formatted', 'Character', '', 'APN_FORMATTED', 'Assessor''s Parcel Number in a formatted form. Dashes and decimals are commonly used to break an APN down into logical components (e.g., 101-32-021.A).', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (5, 'Original Apn', 'OriginalApn', 'Original Apn', 'Character', '', 'ORIGINAL_APN', 'Assessor''s Parcel Number exactly as received by source (e.g., 10132-021A00000).', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (6, 'Previous Parcel Number', 'PreviousParcelNumber', 'Previous Parcel Number', 'Character', '', 'PREVIOUS_PARCEL_NUMBER', 'Previous Parcel ID that is only available for one year.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (7, 'P Id Iris Frmtd', 'PIdIrisFrmtd', 'P Id Iris Frmtd', 'Character', '', 'P_ID_IRIS_FRMTD', 'APN that would link to FACL online products.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (8, 'Account Number', 'AccountNumber', 'Account Number', 'Character', '', 'ACCOUNT_NUMBER', 'The county or source number used primary for billing. Note: this number is typically not unique to a parcel, but rather to a tax bill (multiple parcels can be combined on 1 bill).', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (9, 'Thomas Bros Map Number', 'ThomasBrosMapNumber', 'Thomas Bros Map Number', 'Character', '', 'THOMAS_BROS_MAP_NUMBER', 'The current map page and grid number used by Thomas Bros. Maps company.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (10, 'Map Reference 1', 'MapReference1', 'Map Reference 1', 'Character', '', 'MAP_REFERENCE_1', 'A FARES unique key to link record to the FARES CD Map product. This is typically built from components of the APN that are relevant to the Assessor Maps (e.g., 101-32, represent Map Book and Map Page numbers).', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (11, 'Map Reference 2', 'MapReference2', 'Map Reference 2', 'Character', '', 'MAP_REFERENCE_2', 'A secondary FARES unique key to link property records to the FARES CD Map product. See MAP REFERENCE 1 above.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (12, 'Census Tract', 'CensusTract', 'Census Tract', 'Character', '', 'CENSUS_TRACT', 'Comprised of Census Tract, Census Block and Census Block Suffix. These numbers are established by the US Department of Commerce (Bureau Of The Census).', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (13, 'Block Number', 'BlockNumber', 'Block Number', 'Character', '', 'BLOCK_NUMBER', 'Subdivision or County Map Block Number', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (14, 'Lot Number', 'LotNumber', 'Lot Number', 'Character', '', 'LOT_NUMBER', 'Subdivision or County Map Lot Number', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (15, 'Range', 'Range', 'Range', 'Character', '', 'RANGE', 'The "range" portion of geographical coordinates based on local surveys. Ranges typically run east or west of pre-determined "meridian" in six mile intervals.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (16, 'Township', 'Township', 'Township', 'Character', '', 'TOWNSHIP', 'The "township" portion of geographical coordinates based on local surveys. Townships typically run north or south of pre-determined "meridian" in six mile intervals.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (17, 'Section', 'Section', 'Section', 'Character', '', 'SECTION', 'The "section" portion of geographical coordinates based on local surveys. Sections are 1 square mile and there are 36 sections within the intersection of a Range / Township.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (18, 'Quarter Section', 'QuarterSection', 'Quarter Section', 'Character', '', 'QUARTER_SECTION', 'A section that has been divided into four "sub" sections (e.g., NE, NW, SE, SW).', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (19, 'Flood Zone Community Panel Id', 'FloodZoneCommunityPanelId', 'Flood Zone Community Panel Id', 'Character', '', 'FLOOD_ZONE_COMMUNITY_PANEL_ID', 'This represents the FEMA Community Panel Number.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (20, 'Universal Land Use Code', 'UniversalLandUseCode', 'Universal Land Use Code', 'Character', 'LookupMulti', 'UNIVERSAL_LAND_USE_CODE', 'A FARES established Land Use code converted from various county Land Use codes to aid in search and extract functions. See "LUSE" Table for descriptions', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (21, 'County Land Use 1', 'CountyLandUse1', 'County Land Use 1', 'Character', '', 'COUNTY_LAND_USE_1', 'Primary (i.e., highest) Land Use as established by the county or local taxing administration.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (22, 'County Land Use 2', 'CountyLandUse2', 'County Land Use 2', 'Character', '', 'COUNTY_LAND_USE_2', 'Secondary Land Use as established by the county or local taxing administration.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (23, 'Mobile Home Indicator Flag', 'MobileHomeIndicatorFlag', 'Mobile Home Indicator Flag', 'Character', '', 'MOBILE_HOME_INDICATOR_FLAG', 'This field is populated with a "Y" if a Mobile Home is present on the parcel.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (24, 'Zoning', 'Zoning', 'Zoning', 'Character', '', 'ZONING', 'The data contained in this field is based upon County and/or Local established Zoning Codes and are not converted by FACL', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (25, 'Property Indicator Code', 'PropertyIndicatorCode', 'Property Indicator Code', 'Character', 'LookupMulti', 'PROPERTY_INDICATOR_CODE', 'A FARES general code used to easily recognize specific property types (e.g, Residential, Condominium, Commercial). See "PROPIN" Table for descriptions', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (26, 'Municipality Name', 'MunicipalityName', 'Municipality Name', 'Character', '', 'MUNICIPALITY_NAME', 'Name of the Municipality where parcel is located.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (27, 'Municipality Code', 'MunicipalityCode', 'Municipality Code', 'Character', '', 'MUNICIPALITY_CODE', 'Corresponding Municipality Code (unique within the same county only)', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (28, 'Subdivision Tract Number', 'SubdivisionTractNumber', 'Subdivision Tract Number', 'Character', '', 'SUBDIVISION_TRACT_NUMBER', 'The unique number assigned to a specific subdivision by the county. Often this is used in lieu of an actual subdivision name.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (29, 'Subdivision Plat Book', 'SubdivisionPlatBook', 'Subdivision Plat Book', 'Character', '', 'SUBDIVISION_PLAT_BOOK', 'The first component of a recording system used by some counties to catalog subdivision / condo plans (e.g., Book 123 Page 55A).', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (30, 'Subdivision Plat Page', 'SubdivisionPlatPage', 'Subdivision Plat Page', 'Character', '', 'SUBDIVISION_PLAT_PAGE', 'The second component of a recording system used by some counties to catalog subdivision / condo plans (e.g., Book 123 Page 55A).', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (31, 'Subdivision Name', 'SubdivisionName', 'Subdivision Name', 'Character', '', 'SUBDIVISION_NAME', 'The name of the Subdivision or Condominium where the parcel is located (e.g., Highland Mills Estates, Crystal Towers Condo).', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (32, 'Latitude', 'Latitude', 'Latitude', 'Decimal', '', 'LATITUDE', 'The property location based upon the "latitude" component of latitude/longitude coordinates. The latitude is stored in decimal degrees to 6 decimal places (e.g., 12.123456) and will always be positive north of the North American continent.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (33, 'Longitude', 'Longitude', 'Longitude', 'Decimal', '', 'LONGITUDE', 'The property location based upon the "longitude" component of latitude/longitude coordinates. The longitude is stored in decimal degrees to 6 decimal places (e.g., 123.123456) and will always be negative on the North American continent.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (34, 'Property House Number Prefix', 'PropertyHouseNumberPrefix', 'Property House Number Prefix', 'Character', '', 'Property_HOUSE_NUMBER_PREFIX', 'The digits found to the left of a traditional house number (e.g., A123 MAIN ST) portion of a property address.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (35, 'Property House Number', 'PropertyHouseNumber', 'Property House Number', 'Character', '', 'PROPERTY_HOUSE_NUMBER', 'The digits found to the immediate right of the Property House Number Prefix and to the left of a traditional street name (e.g., A123 MAIN ST).', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (36, 'Property House Number 2', 'PropertyHouseNumber2', 'Property House Number 2', 'Character', '', 'PROPERTY_HOUSE_NUMBER_2', 'The digits found to the immediate right of the Property House Number in rare circumstances such as 123-125 MAIN ST', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (37, 'Property House Number Suffix', 'PropertyHouseNumberSuffix', 'Property House Number Suffix', 'Character', '', 'PROPERTY_HOUSE_NUMBER_SUFFIX', 'The digits found to the right of a traditional house number often representing a multiple or range of entries to a building (e.g., 202B JONES RD, 202-220 JONES RD).', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (38, 'Property Direction', 'PropertyDirection', 'Property Direction', 'Character', '', 'PROPERTY_DIRECTION', 'This field represents the direction found to the left of the street name (e.g., 9340 N DUNHILL DR / 340 NW 70TH AVE). AKA Directional Abbreviations, Pre-Directional.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (39, 'Property Street Name', 'PropertyStreetName', 'Property Street Name', 'Character', '', 'PROPERTY_STREET_NAME', 'The name or number of the street where a parcel is located (e.g., 9340 N DUNHILL DR / 340 NW 70TH AVE / RR BOX 202, 12 BOX CREEK RD).', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (40, 'Property Mode', 'PropertyMode', 'Property Mode', 'Character', '', 'PROPERTY_MODE', 'The Mode or Type of street found to the right of the street name (e.g.., 9340 N DUNHILL DR). AKA Street Designators / Street Suffixes.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (41, 'Property Quadrant', 'PropertyQuadrant', 'Property Quadrant', 'Character', '', 'PROPERTY_QUADRANT', 'The quadrant field is found to the right of Situs Mode (e.g., 100 TEMPLE ST NW, 2040 NW 100 ST SW). AKA Post-Directional.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (42, 'Property Apartment Unit Number', 'PropertyApartmentUnitNumber', 'Property Apartment Unit Number', 'Character', '', 'PROPERTY_APARTMENT_UNIT_NUMBER', 'The unit or suite number of the property address (e.g., 649 LAKE SHORE DR #1400).', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (43, 'Property City', 'PropertyCity', 'Property City', 'Character', '', 'PROPERTY_CITY', 'The city associated with the property address (e.g., CHICAGO, ATLANTA, DENVER).', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (44, 'Property State', 'PropertyState', 'Property State', 'Character', '', 'PROPERTY_STATE', 'The two-letter USPS postal abbreviation associated with the state / protectorants / commonwealth (e.g., CA, VI, PR).', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (45, 'Property Zipcode', 'PropertyZipcode', 'Property Zipcode', 'Character', '', 'PROPERTY_ZIPCODE', 'The nine digit (i.e., ZIP & plus 4) assigned by the USPS. This is populated by various source files and other proprietary and non-proprietary processes (e.g., 954630042).', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (46, 'Property Carrier Route', 'PropertyCarrierRoute', 'Property Carrier Route', 'Character', '', 'PROPERTY_CARRIER_ROUTE', 'This is the four digit code used by the local mail carrier to identify the delivery path.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (47, 'Owner Corporate Indicator Flag', 'OwnerCorporateIndicatorFlag', 'Owner Corporate Indicator Flag', 'Character', '', 'OWNER_CORPORATE_INDICATOR_FLAG', 'The Name of the property owner has been recognized as a corporation or business. See "CORP" Table for descriptions', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (48, 'Owner 1 Last Name', 'Owner1LastName', 'Owner 1 Last Name', 'Character', '', 'OWNER_1_LAST_NAME', 'The name of the property owner.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (49, 'Owner 1 First Name Mi', 'Owner1FirstNameMi', 'Owner 1 First Name Mi', 'Character', '', 'OWNER_1_FIRST_NAME_MI', 'Additional owner names if more than one person owns the property.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (50, 'Owner 2 Last Name', 'Owner2LastName', 'Owner 2 Last Name', 'Character', '', 'OWNER_2_LAST_NAME', 'Non parsed owner name.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (51, 'Owner 2 First Name Mi', 'Owner2FirstNameMi', 'Owner 2 First Name Mi', 'Character', '', 'OWNER_2_FIRST_NAME_MI', 'Additional owner names if more than one person owns the property - non parsed.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (52, 'Absentee Indicator Code', 'AbsenteeIndicatorCode', 'Absentee Indicator Code', 'Character', 'LookupMulti', 'ABSENTEE_INDICATOR_CODE', 'Please see Abesntee Owner Table for Code Descriptions', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (53, 'Owner Phone', 'OwnerPhone', 'Owner Phone', 'Int', '', 'OWNER_PHONE', 'Phone number of property owner (e.g., 9095551212).', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (54, 'Phone Opt Out Indicator', 'PhoneOptOutIndicator', 'Phone Opt Out Indicator', 'Character', 'LookupMulti', 'PHONE_OPT_OUT_INDICATOR', 'A "Y" represents a record where the property owner has registered with the NDNC Registry or contacted the DMA and has asked not to be contacted for phone solicitatns. Please see "PHONEOPTIND" table for code descriptions.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (55, 'Homestead Exempt', 'HomesteadExempt', 'Homestead Exempt', 'Character', '', 'HOMESTEAD_EXEMPT', 'This field will be set with an "Y" if the owner has qualified for a Homeowner/Homestead exemption.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (56, 'Owner Etal Indicator Code', 'OwnerEtalIndicatorCode', 'Owner Etal Indicator Code', 'Character', 'LookupMulti', 'OWNER_ETAL_INDICATOR_CODE', 'A code appearing in this field indicates additional ownership, whose name(s) were not provided by our sources. Please see "ETAL" table for code descriptions.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (57, 'Owner Ownership Rights Code', 'OwnerOwnershipRightsCode', 'Owner Ownership Rights Code', 'Character', 'LookupMulti', 'OWNER_OWNERSHIP_RIGHTS_CODE', 'Form or Method of Property Ownership (e.g., Joint Tenancy, Living Trust). Please see "OWNSH" table for code descriptions.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (58, 'Owner Relationship Type Code', 'OwnerRelationshipTypeCode', 'Owner Relationship Type Code', 'Character', 'LookupMulti', 'OWNER_RELATIONSHIP_TYPE_CODE', 'Relationship between multiple owners or the marital status of a single owner (e.g., Husband/Wife, Unmarried Man). Please see "RELAT" table for code descriptions.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (59, 'Mail House Number Prefix', 'MailHouseNumberPrefix', 'Mail House Number Prefix', 'Character', '', 'MAIL_HOUSE_NUMBER_PREFIX', 'The digits found to the left of a traditional house number (e.g., A123 MAIN ST) portion of a mailing address.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (89, 'Tax Year', 'TaxYear', 'Tax Year', 'Int', '', 'TAX_YEAR', 'The tax year for which the taxes were billed.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (60, 'Mail House Number', 'MailHouseNumber', 'Mail House Number', 'Character', '', 'MAIL_HOUSE_NUMBER', 'The digits found to the immediate right of the Mail House Number Prefix and to the left of a traditional street name (e.g., A123 MAIN ST).', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (61, 'Mail House Number 2', 'MailHouseNumber2', 'Mail House Number 2', 'Character', '', 'MAIL_HOUSE_NUMBER_2', 'The digits found to the immediate right of the Mail House Number in rare circumstances such as 123-125 MAIN ST', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (93, 'Batch Seq', 'BatchSeq', 'Batch Seq', 'Character', '', 'BATCH_SEQ', 'FACL internal sequence number - can be used in the creation of unique keys', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (62, 'Mail House Number Suffix', 'MailHouseNumberSuffix', 'Mail House Number Suffix', 'Character', '', 'MAIL_HOUSE_NUMBER_SUFFIX', 'The digits found to the right of a traditional house number often representing a multiple or range of entries to a building (e.g., 202B JONES RD, 202-220 JONES RD).', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (63, 'Mail Direction', 'MailDirection', 'Mail Direction', 'Character', '', 'MAIL_DIRECTION', 'This field represents the direction found to the left of the street name (e.g., 9340 N DUNHILL DR / 340 NW 70TH AVE). AKA Directional Abbreviations, Pre-Directional.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (64, 'Mail Street Name', 'MailStreetName', 'Mail Street Name', 'Character', '', 'MAIL_STREET_NAME', 'The name or number of the street where a parcel is located (e.g., 9340 N DUNHILL DR / 340 NW 70TH AVE / RR BOX 202, 12 BOX CREEK RD).', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (65, 'Mail Mode', 'MailMode', 'Mail Mode', 'Character', '', 'MAIL_MODE', 'The Mode or Type of street found to the right of the street name (e.g.., 9340 N DUNHILL DR). AKA Street Designators / Street Suffixes.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (66, 'Mail Quadrant', 'MailQuadrant', 'Mail Quadrant', 'Character', '', 'MAIL_QUADRANT', 'The quadrant field is found to the right of Mail Mode (e.g., 100 TEMPLE ST NW, 2040 NW 100 ST SW). AKA Post-Directional.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (67, 'Mail Apartment Unit Number', 'MailApartmentUnitNumber', 'Mail Apartment Unit Number', 'Character', '', 'MAIL_APARTMENT_UNIT_NUMBER', 'The unit or suite number of the mailing address (e.g., 649 LAKE SHORE DR #1400).', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (68, 'Mail City', 'MailCity', 'Mail City', 'Character', '', 'MAIL_CITY', 'The city associated with the mailing address (e.g., CHICAGO, ATLANTA, DENVER).', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (69, 'Mail State', 'MailState', 'Mail State', 'Character', '', 'MAIL_STATE', 'The two-letter USPS postal abbreviation associated with the state / protectorants / commonwealth (e.g., CA, VI, PR).', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (70, 'Mail Zipcode', 'MailZipcode', 'Mail Zipcode', 'Character', '', 'MAIL_ZIPCODE', 'The nine digit (i.e., ZIP & plus 4) assigned by the USPS. This is populated by various source files and other proprietary and non-proprietary processes (e.g., 954630042).', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (71, 'Mail Carrier Route', 'MailCarrierRoute', 'Mail Carrier Route', 'Character', '', 'MAIL_CARRIER_ROUTE', 'This is the four digit code used by the local mail carrier to identify the delivery path.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (72, 'Mail Opt Out Flag', 'MailOptOutFlag', 'Mail Opt Out Flag', 'Character', '', 'MAIL_OPT_OUT_FLAG', 'A "Y" represents a record where the property owner has contacted the DMA (i.e., Direct Marketing Association) and has asked not to be contacted by mail for solicitation. Please see "MAILOPTIND" table for code descriptions.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (73, 'Total Value Calculated', 'TotalValueCalculated', 'Total Value Calculated', 'Int', '', 'TOTAL_VALUE_CALCULATED', 'The "TOTAL" (i.e., Land + Improvement) Value closest to current market value used for assessment by county or local taxing authorities.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (74, 'Land Value Calculated', 'LandValueCalculated', 'Land Value Calculated', 'Int', '', 'LAND_VALUE_CALCULATED', 'The "LAND" Value closest to current market value used for assessment by county or local taxing authorities.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (75, 'Improvement Value Calculated', 'ImprovementValueCalculated', 'Improvement Value Calculated', 'Int', '', 'IMPROVEMENT_VALUE_CALCULATED', 'The "IMPROVEMENT" Value closest to current market value used for assessment by county or local taxing authorities.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (76, 'Total Value Calculated Indicator Flag', 'TotalValueCalculatedIndicatorFlag', 'Total Value Calculated Indicator Flag', 'Character', 'LookupMulti', 'TOTAL_VALUE_CALCULATED_INDICATOR_FLAG', 'The code appearing in this indicator field reflects the type of values (e.g., Market, Appraised) used to seed the TOTAL VALUE CALCULATED field. Please see "VALTY" table for code descriptions.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (77, 'Land Value Calculated Indicator Flag', 'LandValueCalculatedIndicatorFlag', 'Land Value Calculated Indicator Flag', 'Character', '', 'LAND_VALUE_CALCULATED_INDICATOR_FLAG', 'The code appearing in this indicator field reflects the type of values (e.g., Market, Appraised) used to seed the LAND VALUE CALCULATED field. Please see "VALTY" table for code descriptions.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (78, 'Improvement Value Calculated Indicator Flag', 'ImprovementValueCalculatedIndicatorFlag', 'Improvement Value Calculated Indicator Flag', 'Character', '', 'IMPROVEMENT_VALUE_CALCULATED_INDICATOR_FLAG', 'The code appearing in this indicator field reflects the type of values (e.g., Market, Appraised) used to seed the IMPROVEMENT VALUE CALCULATED field. Please see "VALTY" table for code descriptions.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (79, 'Assd Total Value', 'AssdTotalValue', 'Assd Total Value', 'Int', '', 'ASSD_TOTAL_VALUE', 'The Total Assessed Value of the Parcel''s Land & Improvement values as provided by the county or local taxing/assessment authority.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (80, 'Assd Land Value', 'AssdLandValue', 'Assd Land Value', 'Int', '', 'ASSD_LAND_VALUE', 'The Assessed Land Values as provided by the county or local taxing/assessment authority.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (81, 'Assd Improvement Value', 'AssdImprovementValue', 'Assd Improvement Value', 'Int', '', 'ASSD_IMPROVEMENT_VALUE', 'The Assessed Improvement Values as provided by the county or local taxing/assessment authority.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (82, 'Mkt Total Value', 'MktTotalValue', 'Mkt Total Value', 'Int', '', 'MKT_TOTAL_VALUE', 'The Total Market Value of the Parcel''s Land & Improvement values as provided by the county or local taxing/assessment authority.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (83, 'Mkt Land Value', 'MktLandValue', 'Mkt Land Value', 'Int', '', 'MKT_LAND_VALUE', 'The Market Land Values as provided by the county or local taxing/assessment authority.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (84, 'Mkt Improvement Value', 'MktImprovementValue', 'Mkt Improvement Value', 'Int', '', 'MKT_IMPROVEMENT_VALUE', 'The Market Improvement Values as provided by the county or local taxing/assessment authority.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (85, 'Appr Total Value', 'ApprTotalValue', 'Appr Total Value', 'Int', '', 'APPR_TOTAL_VALUE', 'The Total Appraised Value of the Parcel''s Land & Improvement values as provided by the county or local taxing/assessment authority.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (86, 'Appr Land Value', 'ApprLandValue', 'Appr Land Value', 'Int', '', 'APPR_LAND_VALUE', 'The Appraised Land Values as provided by the county or local taxing/assessment authority.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (87, 'Appr Improvement Value', 'ApprImprovementValue', 'Appr Improvement Value', 'Int', '', 'APPR_IMPROVEMENT_VALUE', 'The Appraised Improvement Values as provided by the county or local taxing/assessment authority.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (88, 'Tax Amount', 'TaxAmount', 'Tax Amount', 'Decimal', '', 'TAX_AMOUNT', 'The Total Tax amount provided by the county or local taxing/assessment authority.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (90, 'Assessed Year', 'AssessedYear', 'Assessed Year', 'Int', '', 'ASSESSED_YEAR', 'The assessment year for which the taxes were billed.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (91, 'Tax Code Area', 'TaxCodeArea', 'Tax Code Area', 'Character', '', 'TAX_CODE_AREA', 'This is a county specific code that represent the tax entity(s) for which a parcel is taxed (e.g., Park Hosp Dist, Hall Sch Dist,).', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (92, 'Batch Id', 'BatchId', 'Batch Id', 'Character', '', 'BATCH_ID', 'FACL internal date number - can be used in the creation of unique keys', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (94, 'Multi Apn Flag Code', 'MultiApnFlagCode', 'Multi Apn Flag Code', 'Character', 'LookupMulti', 'MULTI_APN_FLAG_CODE', 'The data contained in this field depicts multiple or split parcel sales. Please see "SLMLT" table for code descriptions.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (95, 'Document Number', 'DocumentNumber', 'Document Number', 'Character', '', 'DOCUMENT_NUMBER', 'The document number used by some counties to record sales transactions (e.g., 000012345678).', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (96, 'Book Page', 'BookPage', 'Book Page', 'Character', '', 'BOOK_PAGE', 'The Book and Page number used by some counties to catalog their sales recordings (e.g., 001234005678).', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (97, 'Sales Document Type Code', 'SalesDocumentTypeCode', 'Sales Document Type Code', 'Character', 'LookupMulti', 'DOCUMENT_TYPE', 'The type of deed used to record the sales transaction (e.g., Grant, Quit, Foreclosure). Please see "DEEDC" table for code descriptions.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (98, 'Recording Date', 'RecordingDate', 'Recording Date', 'DateTime', '', 'RECORDING_DATE', 'The date the sales transaction was recorded at the county (e.g., 19621028)', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (99, 'Sale Date', 'SaleDate', 'Sale Date', 'DateTime', '', 'SALE_DATE', 'The date the sales transaction was legally completed (i.e., contact signed) (e.g., 19621025).', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (100, 'Sale Amount', 'SaleAmount', 'Sale Amount', 'Int', '', 'SALE_AMOUNT', 'Price of the sale as depicted on the recorded sales transaction.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (101, 'Sale Code', 'SaleCode', 'Sale Code', 'Character', 'LookupMulti', 'SALES_CODE', 'This field indicates what the financial consideration is.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (102, 'Seller Name', 'SellerName', 'Seller Name', 'Character', '', 'SELLER_NAME', 'The seller''s name as it appears on the recorded sales transaction.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (103, 'Sales Transaction Type Code', 'SalesTransactionTypeCode', 'Sales Transaction Type Code', 'Character', 'LookupMulti', 'TRANSACTION_TYPE', 'This identifies situations associated with the sale (e.g., Resale, Construction Loan, Seller Carryback). Please see "TRNTP" table for code descriptions.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (104, 'Title Company Code', 'TitleCompanyCode', 'Title Company Code', 'Character', '', 'TITLE_COMPANY_CODE', 'This is a FARES internal code used to identify the Title Company that was associated with the sales transaction.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (105, 'Title Company Name', 'TitleCompanyName', 'Title Company Name', 'Character', '', 'TITLE_COMPANY_NAME', 'This is the Title Company associated with the sales transaction', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (106, 'Residential Model Indicator Flag', 'ResidentialModelIndicatorFlag', 'Residential Model Indicator Flag', 'Character', '', 'RESIDENTIAL_MODEL_INDICATOR_FLAG', 'A code to indicate whether the property is residential based on individual zipcodes and values. "Y" = yes, "N" or blank = no', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (108, '1st Mortgage Date', '1stMortgageDate', '1st Mortgage Date', 'DateTime', '', '1ST_MORTGAGE_DATE', 'The date the Mortgage was initiated.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (107, '1st Mortgage Amount', '1stMortgageAmount', '1st Mortgage Amount', 'Int', '', '1ST_MORTGAGE_AMOUNT', 'The amount of the first mortgage as depicted on the recorded document.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (109, '1st Mortgage Loan Type Code', '1stMortgageLoanTypeCode', '1st Mortgage Loan Type Code', 'Character', 'LookupMulti', 'MORTGAGE_LOAN_TYPE_CODE', 'Type of load secured (e.g., Conventional, FHA, VA). Please see "MTGTP" table for code descriptions', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (110, '1st Mortgage Deed Type Code', '1stMortgageDeedTypeCode', '1st Mortgage Deed Type Code', 'Character', 'LookupMulti', 'MORTGAGE_DEED_TYPE_CODE', 'Type of deed used for recording (e.g., Agreement of Sale, Assumption, Correction Deed). Please see "DETDOCTYP" table for code descriptions', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (111, '1st Mortgage Term Code', '1stMortgageTermCode', '1st Mortgage Term Code', 'Character', 'LookupMulti', 'MORTGAGE_TERM_CODE', 'This code is used to identify whether the number stored in the MORTGAGE TERM field is in Days, Months or Years. Please see "MTGTC" table for code descriptions.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (112, '1st Mortgage Term', '1stMortgageTerm', '1st Mortgage Term', 'Int', '', '1ST_MORTGAGE_TERM', 'The length of time before the mortgage matures (e.g., 15yrs, 30 yrs, 45dys).', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (113, '1st Mortgage Due Date', '1stMortgageDueDate', '1st Mortgage Due Date', 'DateTime', '', '1ST_MORTGAGE_DUE_DATE', 'The date the mortgage amount becomes due.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (114, '1st Mortage Assumption Amount', '1stMortageAssumptionAmount', '1st Mortage Assumption Amount', 'Int', '', '1ST_MORTAGE_ASSUMPTION_AMOUNT', 'The assumption amount related to an existing mortgage.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (115, '1st Mortgage Lender Company Code', '1stMortgageLenderCompanyCode', '1st Mortgage Lender Company Code', 'Character', '', '1ST_MORTGAGE_LENDER_COMPANY_CODE', 'This is a FARES internal code used to identify the Lending Company that was associated with the sales transaction.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (116, '1st Mortgage Lender Name', '1stMortgageLenderName', '1st Mortgage Lender Name', 'Character', '', '1ST_MORTGAGE_LENDER_NAME', 'This is the name of the lender on the original recorded document.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (117, '2nd Mortgage Amount', '2ndMortgageAmount', '2nd Mortgage Amount', 'Int', '', '2ND_MORTGAGE_AMOUNT', 'This is the amount associated with the 2nd mortgage.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (118, '2nd Mortgage Loan Type Code', '2ndMortgageLoanTypeCode', '2nd Mortgage Loan Type Code', 'Character', 'LookupMulti', 'MORTGAGE_LOAN_TYPE_CODE', 'Type of load secured as part of the 2nd mortgage (e.g., Conventional, FHA, VA). Please see "MTGTP" table for code descriptions', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (119, '2nd Deed Type Code', '2ndDeedTypeCode', '2nd Deed Type Code', 'Character', 'LookupMulti', 'MORTGAGE_DEED_TYPE_CODE', 'Type of deed used for recording the 2nd mortgage (e.g., Agreement of Sale, Assumption, Correction Deed). Please see "DOCTY" table for code descriptions', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (121, 'Prior Batch Seq', 'PriorBatchSeq', 'Prior Batch Seq', 'Character', '', 'PRIOR_BATCH_SEQ', 'FACL internal sequence number - can be used in the creation of unique keys', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (120, 'Prior Batch Id', 'PriorBatchId', 'Prior Batch Id', 'Character', '', 'PRIOR_BATCH_ID', 'FACL internal date number - can be used in the creation of unique keys', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (122, 'Prior Sale Document Number', 'PriorSaleDocumentNumber', 'Prior Sale Document Number', 'Character', '', 'PRIOR_SALE_DOCUMENT_NUMBER', 'The document number used by some counties to record sales transactions (e.g., 000012345678).', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (123, 'Prior Sale Book Page', 'PriorSaleBookPage', 'Prior Sale Book Page', 'Character', '', 'PRIOR_SALE_BOOK_PAGE', 'The Book and Page number used by some counties to catalog their sales recordings (e.g., 001234005678).', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (155, 'Bath Fixtures', 'BathFixtures', 'Bath Fixtures', 'Int', '', 'BATH_FIXTURES', 'The total number of bathroom fixtures (typically a Full Bath would have 4 fixtures - 1 = sink, 1 = toilet, 1 = bathtub, 1 = shower head).', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (124, 'Prior Sale Document Type Code', 'PriorSaleDocumentTypeCode', 'Prior Sale Document Type Code', 'Character', '', 'DOCUMENT_TYPE', 'The type of deed used to record the prior sales transaction (e.g., Grant, Quit, Foreclosure). Please see "DEEDC" table for code descriptions.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (125, 'Prior Sale Recording Date', 'PriorSaleRecordingDate', 'Prior Sale Recording Date', 'DateTime', '', 'PRIOR_SALE_RECORDING_DATE', 'The date the sales transaction was recorded at the county (e.g., 19621028)', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (126, 'Prior Sale Date', 'PriorSaleDate', 'Prior Sale Date', 'DateTime', '', 'PRIOR_SALE_DATE', 'The date the sales transaction was legally completed (i.e., contact signed) (e.g., 19621025).', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (127, 'Prior Sale Amount', 'PriorSaleAmount', 'Prior Sale Amount', 'Int', '', 'PRIOR_SALE_AMOUNT', 'Price of the sale as depicted on the recorded sales transaction.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (128, 'Prior Sale Code', 'PriorSaleCode', 'Prior Sale Code', 'Character', '', 'PRIOR_SALE_CODE', 'This field indicates whether the financial consideration is F = Full or P = Partial.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (129, 'Prior Sale Transaction Type Code', 'PriorSaleTransactionTypeCode', 'Prior Sale Transaction Type Code', 'Character', 'LookupMulti', 'TRANSACTION_TYPE', 'This identifies situations associated with the sale (e.g., Resale, Construction Loan, Seller Carryback). Please see "TRNTP" table for code descriptions.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (130, 'Prior Sale Mortgage Amount', 'PriorSaleMortgageAmount', 'Prior Sale Mortgage Amount', 'Int', '', 'PRIOR_SALE_MORTGAGE_AMOUNT', 'This is the amount associated with the mortgage of the prior sale.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (132, 'Depth Footage', 'DepthFootage', 'Depth Footage', 'Int', '', 'DEPTH_FOOTAGE', 'The linear feet between the front and back of the lot.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (131, 'Front Footage', 'FrontFootage', 'Front Footage', 'Int', '', 'FRONT_FOOTAGE', 'The linear feet across the front of the lot - facing the street.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (133, 'Acres', 'Acres', 'Acres', 'Decimal', '', 'ACRES', 'Total land mass in Acres.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (134, 'Land Square Footage', 'LandSquareFootage', 'Land Square Footage', 'Int', '', 'LAND_SQUARE_FOOTAGE', 'Total land mass is Square Feet.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (135, 'Lot Area', 'LotArea', 'Lot Area', 'Character', '', 'LOT_AREA', 'A textual description of the lot area, which may include size and unique attributes of the lot (e.g., irregular lot size).', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (137, 'Universal Building Square Feet Indicator Code', 'UniversalBuildingSquareFeetIndicatorCode', 'Universal Building Square Feet Indicator Code', 'Character', 'LookupMulti', 'UNIVERSAL_BUILDING_SQUARE_FEET_INDICATOR_CODE', 'The codes appearing in this field indicates the source used to populate the UNIVERSAL BUILDING SQUARE FEET field (e.g., Living, Adjusted, Gross). Please see "BLDSF" table for code descriptions.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (136, 'Universal Building Square Feet', 'UniversalBuildingSquareFeet', 'Universal Building Square Feet', 'Int', '', 'UNIVERSAL_BUILDING_SQUARE_FEET', 'The Building Square Footage that can most accurately be used for assessments or comparables (e.g., Living, Adjusted, Gross).', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (138, 'Building Square Feet', 'BuildingSquareFeet', 'Building Square Feet', 'Int', '', 'BUILDING_SQUARE_FEET', 'The size of the building in Square Feet. This field is most commonly populated as a cumulative total when a county does not differentiate between Living and Non-living areas.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (139, 'Living Square Feet', 'LivingSquareFeet', 'Living Square Feet', 'Int', '', 'LIVING_SQUARE_FEET', 'This is the area of a building that is used for general living. This is typically the area of a building that is heated or air conditioned and generally does not include Garage, Porch or Unfinished Basement Square Footage values.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (140, 'Ground Floor Square Feet', 'GroundFloorSquareFeet', 'Ground Floor Square Feet', 'Int', '', 'GROUND_FLOOR_SQUARE_FEET', 'Square footage of the part of the building which is level with the ground (typically the front of the building). This is generally above the basement(s) and below the second floor.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (141, 'Gross Square Feet', 'GrossSquareFeet', 'Gross Square Feet', 'Int', '', 'GROSS_SQUARE_FEET', 'This is the square footage for the entire building. Typically this represents all square feet under the roof.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (142, 'Adjusted Gross Square Feet', 'AdjustedGrossSquareFeet', 'Adjusted Gross Square Feet', 'Int', '', 'ADJUSTED_GROSS_SQUARE_FEET', 'This is the square footage used by the county or local taxing / assessment authority to determine Improvement Value. This figure is typically 100% of the living area, plus lower percentage of non-living area.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (143, 'Basement Square Feet', 'BasementSquareFeet', 'Basement Square Feet', 'Int', '', 'BASEMENT_SQUARE_FEET', 'This is total square footage associated with Basement portion of a building. This would include both finished and unfinished areas.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (144, 'Garage Parking Square Feet', 'GarageParkingSquareFeet', 'Garage Parking Square Feet', 'Int', '', 'GARAGE_PARKING_SQUARE_FEET', 'This is the total square footage of the primary garage or parking area (i.e., commercial). This includes both finished and unfinished areas.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (146, 'Effective Year Built', 'EffectiveYearBuilt', 'Effective Year Built', 'Int', '', 'EFFECTIVE_YEAR_BUILT', 'This is the first year the building was assessed with its current components (e.g., a building is originally constructed in 1960 and a bedroom and bath was added to the building in 1974. The Year Built would be 1960 and the Effective Year Built would be 1974.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (145, 'Year Built', 'YearBuilt', 'Year Built', 'Int', '', 'YEAR_BUILT', 'This is the construction year of the original building.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (147, 'Bedrooms', 'Bedrooms', 'Bedrooms', 'Int', '', 'BEDROOMS', 'Total number of bedroom contained in the primary building.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (148, 'Total Rooms', 'TotalRooms', 'Total Rooms', 'Int', '', 'TOTAL_ROOMS', 'Total number of rooms contained in the primary building.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (149, 'Total Baths Calculated', 'TotalBathsCalculated', 'Total Baths Calculated', 'Int', '', 'TOTAL_BATHS_CALCULATED', 'Total number of Bath Rooms in whole numbers (e.g., a home containing 2 1/2 baths would have the number 3 stored in this field as, three actual rooms have been designated for this purpose).', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (150, 'Total Baths', 'TotalBaths', 'Total Baths', 'Int', '', 'TOTAL_BATHS', 'Total number of Bathrooms as provided by our data sources (e.g., 4.00, 2.50, 1.75).', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (151, 'Full Baths', 'FullBaths', 'Full Baths', 'Int', '', 'FULL_BATHS', 'Total number of Full Baths (typically comprised of a sink, toilet, and bathtub / shower stall). A home containing 2 1/2 baths would have the number 2 stored in this field.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (152, 'Half Baths', 'HalfBaths', 'Half Baths', 'Int', '', 'HALF_BATHS', 'Total number of Half Baths (typically comprised of a sink & toilet). A home containing 2 1/2 baths would have the number 1 stored in this field.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (153, '1 Qtr Baths', '1QtrBaths', '1 Qtr Baths', 'Int', '', '1QTR_BATHS', 'Total number of Quarter Baths (typically comprised only of a sink, as found in many laundry rooms).', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (154, '3 Qtr Baths', '3QtrBaths', '3 Qtr Baths', 'Int', '', '3QTR_BATHS', 'Total number of 3 Quarter Baths (typically comprised of a sink, toilet & shower stall).', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (156, 'Air Conditioning Code', 'AirConditioningCode', 'Air Conditioning Code', 'Character', 'LookupMulti', 'AIR_CONDITIONING_CODE', 'The type of air conditioning method used to cool the building (e.g., Central, Wall Unit, Evaporative). Please see "ANCHO" table for code descriptions.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (157, 'Basement Finish Code', 'BasementFinishCode', 'Basement Finish Code', 'Character', 'LookupMulti', 'BASEMENT_FINISH_CODE', 'The type of basement found in the building (e.g., Finished, Half, Crawl). Please see "BSMTF" table for code descriptions.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (158, 'Bldg Code', 'BldgCode', 'Bldg Code', 'Character', 'LookupMulti', 'BLDG_CODE', 'The primary building type (e.g., Bowling Alley, Supermarket). Please see "BISCO" table for code descriptions.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (159, 'Bldg Improvement Code', 'BldgImprovementCode', 'Bldg Improvement Code', 'Character', 'LookupMulti', 'BLDG_IMPROVEMENT_CODE', 'The primary improvement type (e.g., Grain Silo, Hanger, Marina). Please see "BISCO" table for code descriptions.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (160, 'Condition Code', 'ConditionCode', 'Condition Code', 'Character', 'LookupMulti', 'CONDITION_CODE', 'This represent the physical condition of the mail improvement (e.g., Good, Fair, Under Construction). Please see "COND" table for code descriptions.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (161, 'Construction Type Code', 'ConstructionTypeCode', 'Construction Type Code', 'Character', 'LookupMulti', 'CONSTRUCTION_TYPE_CODE', 'The primary method of construction (e.g., Steel / Glass, Concrete Block, Log). Please see "CNSTR" table for code descriptions.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (162, 'Exterior Walls Code', 'ExteriorWallsCode', 'Exterior Walls Code', 'Character', 'LookupMulti', 'EXTERIOR_WALLS_CODE', 'The type and/or finish of the exterior walls (e.g., Vinyl Siding, Brick Veneer, Frame / Stone). Please see "EXTNW" table for code descriptions.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (163, 'Fireplace Indicator Flag', 'FireplaceIndicatorFlag', 'Fireplace Indicator Flag', 'Character', '', 'FIREPLACE_INDICATOR_FLAG', 'This field is populated with a "Y" if a fireplace is located within the building.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (164, 'Fireplace Number', 'FireplaceNumber', 'Fireplace Number', 'Int', '', 'FIREPLACE_NUMBER', 'This represent the number of fireplace openings located within the building', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (165, 'Fireplace Type Code', 'FireplaceTypeCode', 'Fireplace Type Code', 'Character', 'LookupMulti', 'FIREPLACE_TYPE_CODE', 'The type of fireplace (e.g., 2 Story / 3 Openings, 2 Story Brick). Please see "FIREP" table for code descriptions.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (166, 'Foundation Code', 'FoundationCode', 'Foundation Code', 'Character', 'LookupMulti', 'FOUNDATION_CODE', 'The type of foundation (e.g., Continuous Footing, Pier, Mud Sill). Please see "FOUND" table for code descriptions.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (167, 'Floor Code', 'FloorCode', 'Floor Code', 'Character', 'LookupMulti', 'FLOOR_CODE', 'The type of floor construction (e.g., Concrete, Plywood). Please see "FLTYP" table for code descriptions.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (168, 'Frame Code', 'FrameCode', 'Frame Code', 'Character', 'LookupMulti', 'FRAME_CODE', 'The type of roof framing used (e.g., Bar Joist, Reinforced Concrete, Flexicore). Please see "RFFRM" table for code descriptions.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (169, 'Garage Code', 'GarageCode', 'Garage Code', 'Character', 'LookupMulti', 'GARAGE_CODE', 'Type of garage or carport present (e.g., Attached Finished, Enclosed Carport, Basement Garage). Please see "GNPCO" table for code descriptions.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (170, 'Heating Code', 'HeatingCode', 'Heating Code', 'Character', 'LookupMulti', 'HEATING_CODE', 'Type or method of heating (e.g., Hot Water, Heat Pump, Baseboard, Radiant). Please see "ANHCO" table for code descriptions.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (171, 'Parking Spaces', 'ParkingSpaces', 'Parking Spaces', 'Int', '', 'PARKING_SPACES', 'This represent the total number of Parking Spaces or Car Capacity associated with the Garage or Parking type.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (172, 'Parking Type Code', 'ParkingTypeCode', 'Parking Type Code', 'Character', 'LookupMulti', 'PARKING_TYPE_CODE', 'Type of parking found on the parcel. This is typically commercial or communal (e.g., Condos) in nature. Please see "GNPCO" table for code descriptions.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (173, 'Pool Flag', 'PoolFlag', 'Pool Flag', 'Character', '', 'POOL_FLAG', 'This field is populated with a "Y" if a Pool is present on the parcel', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (174, 'Pool Code', 'PoolCode', 'Pool Code', 'Character', 'LookupMulti', 'POOL_CODE', 'Type of pool, construction or pool amenities (e.g., Kidney, Gunite, Vinyl, Jacuzzi, Heated). Please see "POOL" table for code descriptions.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (175, 'Quality Code', 'QualityCode', 'Quality Code', 'Character', 'LookupMulti', 'QUALITY_CODE', 'Type of construction quality of building (e.g., excellent, economical). Please see "QUAL" table for code descriptions.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (176, 'Roof Cover Code', 'RoofCoverCode', 'Roof Cover Code', 'Character', 'LookupMulti', 'ROOF_COVER_CODE', 'Type of roof covering (e.g., Clay Tile, Aluminum, Shake). Please see "RFCO" table for code descriptions.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (177, 'Roof Type Code', 'RoofTypeCode', 'Roof Type Code', 'Character', 'LookupMulti', 'ROOF_TYPE_CODE', 'Type of roof shape (e.g., Gambrel, Gable, Flat, Mansard). Please see "RFCO" table for code descriptions.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (178, 'Stories Code', 'StoriesCode', 'Stories Code', 'Character', 'LookupMulti', 'STORIES_CODE', 'Type / number of stories (e.g., Split Foyer, Tri Level, 2 Story). Please see "STORY" table for code descriptions.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (179, 'Stories Number', 'StoriesNumber', 'Stories Number', 'Decimal', '', 'STORIES_NUMBER', 'Number of stories associated with the building (e.g., 2, 1.5).', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (180, 'View', 'View', 'View', 'Character', 'LookupMulti', 'VIEW', 'View from building (e.g., Gulf, Mountains, Pool). Please see "LIVS" table for code descriptions.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (181, 'Location Influence Code', 'LocationInfluenceCode', 'Location Influence Code', 'Character', 'LookupMulti', 'LOCATION_INFLUENCE_CODE', 'Positive or negative aspects associated with the location of the parcel (e.g., waterfront, flood plane, airport). Please see "LIVS" table for code descriptions.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (182, 'Number Of Units', 'NumberOfUnits', 'Number Of Units', 'Int', '', 'NUMBER_OF_UNITS', 'Total number of buildings on the parcel.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (183, 'Style Code', 'StyleCode', 'Style Code', 'Character', 'LookupMulti', 'STYLE_CODE', 'Type of building style (e.g., Colonial, Cape Code, Bungalow). Please see "STYLE" table for code descriptions.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (184, 'Units Number', 'UnitsNumber', 'Units Number', 'Int', '', 'UNITS_NUMBER', 'Number of Residential, Apartment or Business Units.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (185, 'Electric Energy Code', 'ElectricEnergyCode', 'Electric Energy Code', 'Character', 'LookupMulti', 'ALL_UTILITY', 'Type of electricity or energy use within the building (e.g., Average Wiring, Underground Wired, Private Source). Please see "ELEC" table for code descriptions. See also "UTIL" table', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (186, 'Fuel Code', 'FuelCode', 'Fuel Code', 'Character', 'LookupMulti', 'ALL_UTILITY', 'Type of fuel used for heating of water and building (e.g., Solar, Gas, Oil). Please see "FUEL" table for code descriptions. See also "UTIL" table', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (187, 'Sewer Code', 'SewerCode', 'Sewer Code', 'Character', 'LookupMulti', 'ALL_UTILITY', 'Type of sewer system on the parcel (e.g., Public, Septic, Commercial). Please see "SEWER" table for code descriptions. See also "UTIL" table', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (188, 'Water Code', 'WaterCode', 'Water Code', 'Character', 'LookupMulti', 'ALL_UTILITY', 'Type of water service on the parcel (e.g., Public, Well, Cistern). Please see "WATER" table for code descriptions. See also "UTIL" table', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (190, 'Legal 2', 'Legal2', 'Legal 2', 'Character', '', 'LEGAL_2', 'Second 250 bytes of the total 750 byte legal description.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (189, 'Legal 1', 'Legal1', 'Legal 1', 'Character', '', 'LEGAL_1', 'First 250 bytes of the total 750 byte legal description.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (191, 'Legal 3', 'Legal3', 'Legal 3', 'Character', '', 'LEGAL_3', 'Third 250 bytes of the total 750 byte legal description.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (192, 'Filler 01', 'Filler01', 'Filler 01', 'Character', '', 'FILLER01', 'Filler field.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (193, 'Filler 02', 'Filler02', 'Filler 02', 'Character', '', 'FILLER02', 'Filler field.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (194, 'Filler 03', 'Filler03', 'Filler 03', 'Character', '', 'FILLER03', 'Filler field.', 'CoreLogic', 'county', 'tax');
INSERT INTO data_source_fields ("MetadataEntryID", "SystemName", "ShortName", "LongName", "DataType", "Interpretation", "LookupName", "Description", data_source_id, data_source_type, data_list_type) VALUES (195, 'Filler 04', 'Filler04', 'Filler 04', 'Character', '', 'FILLER04', 'Filler field.', 'CoreLogic', 'county', 'tax');


--
-- Name: data_source_fields_MetadataEntryID_seq; Type: SEQUENCE SET; Schema: public; Owner: dev
--

SELECT pg_catalog.setval('"data_source_fields_MetadataEntryID_seq"', 1, false);


--
-- PostgreSQL database dump complete
--

